-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--PROYECTO 3- LENGUAJES DE BASES DE DATOS - JUAN PABLO VINDAS SUAREZ, SEBASTIAN SEGURA SAENZ, ROGER FERNANDO PEREIRA SANCHES, MATIAS VARGAS UMANA
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------
-- CREACION DE USUARIOS Y ASIGNACION DE ROLES.
--------------------------------------------------------
// Asignacion de permisos para crear el usuario 
alter session set "_ORACLE_SCRIPT"=true;

// Creacion del usuario
CREATE USER usuarioDondePapa IDENTIFIED BY "4567.";

// Asignacion de permisos de usuario 
GRANT CONNECT, RESOURCE TO usuarioDondePapa;
GRANT DBA TO usuarioDondePapa;

--------------------------------------------------------
-- CREACION DE TABLAS
--------------------------------------------------------
// CATEGORIA
CREATE TABLE usuarioDondePapa.categoria (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR2(255),
    disponible NUMBER(1),
    ruta_imagen VARCHAR2(1024)
);

// PLATO
CREATE TABLE usuarioDondePapa.plato (
    id_plato NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria NUMBER NOT NULL,
    descripcion VARCHAR2(255) NOT NULL,
    detalle VARCHAR2(1600) NOT NULL,
    precio NUMBER,
    existencias NUMBER NOT NULL,
    ruta_imagen VARCHAR2(1024),
    disponible NUMBER(1)
);

// RESERVACION
CREATE TABLE usuarioDondePapa.reservacion (
    id_reservacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255),
    hora TIME,
    numero_de_mesa NUMBER,
    contacto VARCHAR2(255)
);


// USUARIO
CREATE TABLE usuarioDondePapa.usuario (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(20) NOT NULL,
    password VARCHAR2(512) NOT NULL,
    nombre VARCHAR2(20) NOT NULL,
    apellidos VARCHAR2(30) NOT NULL,
    correo VARCHAR2(1024),
    telefono VARCHAR2(15),
    ruta_imagen VARCHAR2(1024),
    activo NUMBER(1)
);

// FACTURA
CREATE TABLE usuarioDondePapa.factura (
    id_factura NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    fecha DATE,
    total NUMBER,
    estado NUMBER
);

// VENTA
CREATE TABLE usuarioDondePapa.venta (
    id_venta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_factura NUMBER NOT NULL,
    id_plato NUMBER NOT NULL,
    precio NUMBER,
    cantidad NUMBER
);

// ROL
CREATE TABLE usuarioDondePapa.rol (
    id_rol NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(20),
    id_usuario NUMBER
);

// TRANSACCION
CREATE TABLE usuarioDondePapa.transacciones (
    id_transaccion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    tipo VARCHAR2(50),
    monto NUMBER(10, 2),
    fecha DATE,
    descripcion VARCHAR2(255)
);

--------------------------------------------------------
-- PRIMARY KEYS & FOREIGN KEYS
--------------------------------------------------------

// PLATO
ALTER TABLE usuarioDondePapa.plato
ADD CONSTRAINT fk_producto_categoria FOREIGN KEY (id_categoria) REFERENCES usuarioDondePapa.categoria(id_categoria);

// FACTURA
ALTER TABLE usuarioDondePapa.factura
ADD CONSTRAINT fk_factura_usuario FOREIGN KEY (id_usuario) REFERENCES usuarioDondePapa.usuario(id_usuario);

// VENTA
ALTER TABLE usuarioDondePapa.venta
ADD CONSTRAINT fk_ventas_factura FOREIGN KEY (id_factura) REFERENCES usuarioDondePapa.factura(id_factura);
ALTER TABLE usuarioDondePapa.venta
ADD CONSTRAINT fk_ventas_plato FOREIGN KEY (id_plato) REFERENCES usuarioDondePapa.plato(id_plato);

// ROL
ALTER TABLE usuarioDondePapa.rol
ADD CONSTRAINT fk_rol_usuario FOREIGN KEY (id_usuario) REFERENCES usuarioDondePapa.usuario(id_usuario);

// TRANSACCIONES
ALTER TABLE usuarioDondePapa.transacciones
ADD CONSTRAINT fk_transacciones_usuario FOREIGN KEY (id_usuario) REFERENCES usuarioDondePapa.usuario(id_usuario);

--------------------------------------------------------
-- INSERTS
--------------------------------------------------------

//CATEGORIA

-- Inserts en la tabla categoria
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES ('Sandwiches', 1, 'https://i.blogs.es/1cbc97/collage_sanwich/1366_2000.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES ('Sopas', 1, 'https://i.blogs.es/4f9a7f/collage-seis-fotos-portada-dap/650_1200.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES ('Wraps', 1, 'https://www.gourmet.cl/wp-content/uploads/2016/09/wrap-de-pollo.jpg-editada.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES ('Quesadillas', 1, 'https://www.lechedeflorida.com/core/fileparse.php/267/urlt/BBQ-PORK-QUESADILLA-web.png');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES ('Ticos', 1, 'https://i.ytimg.com/vi/VCIc5JO_6pQ/maxresdefault.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES ('Arroz', 1, 'https://www.ecestaticos.com/image/clipping/1440/1080/c45466fb9f76baa6eebf80a4194592d7/los-trucos-para-que-te-quede-el-arroz-perfecto.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES ('Mariscos', 1, 'https://www.eluniversal.com.mx/resizer/04M0CFm2P8H_U3CdE4co_RWqRkQ=/1100x666/cloudfront-us-east-1.images.arcpublishing.com/eluniversal/PEKLULINHNCMHM3DVNV6ORRI5M.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES ('Pastas', 1, 'https://casadiromavlc.com/wp-content/uploads/2019/08/tipos-de-pastas-y-salsas-cover-1080x675.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES ('Pollos', 1, 'https://s1.eestatic.com/2015/06/10/cocinillas/cocinillas_40006005_116187701_1706x960.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES ('Hamburguesas', 1, 'https://cdn2.cocinadelirante.com/sites/default/files/images/2023/08/recetas-de-hamburguesas-caseras.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES ('Carnes', 1, 'https://img.freepik.com/foto-gratis/carne-cruda-mesa_23-2150857912.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES ('Guarniciones', 1, 'https://static.bonviveur.es/tags/las-mejores-recetas-de-guarniciones.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES ('Especial', 1, 'https://previews.123rf.com/images/acceptphoto/acceptphoto1703/acceptphoto170300049/73290879-variedad-de-platos-especiales-en-peque%C3%B1as-placas-blancas.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES ('Para Picar', 1, 'https://hips.hearstapps.com/hmg-prod/images/huevos-rellenos-de-hummus-1552479730.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES ('Bocas del mar', 1, 'https://www.bocasdelmar.com/wp-content/uploads/2019/01/eatandrink2.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES ('tacos gallos', 1, 'https://www.cocinatis.com/archivos/202207/tacos-mexicanos-con-pico-gallo_large_16x9.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES ('Bocas y tierra tica', 1, 'https://media-cdn.tripadvisor.com/media/photo-s/1b/4e/54/49/plato-de-bocas-surtido.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES ('Bocas clasicas', 1, 'https://enbocacr.com/wp-content/uploads/2023/06/platos-enboca-2023-1.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES ('Bebidas Donde Papï¿½', 1, 'https://aprende.com/wp-content/uploads/2022/10/bebidas-naturales.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES ('Licores', 1, 'https://thefoodtech.com/wp-content/uploads/2020/05/productos-diaego.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES ('Postres', 1, 'https://i.blogs.es/1c733d/postres/1366_2000.jpg');

//PLATO
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Ensalada César', 'Con quesito parmesano y cuadritos de pan tostado con nuestro pollo grill.', 4500, 10, 1, 1, 'https://www.gourmet.cl/wp-content/uploads/2016/09/Ensalada_C%C3%A9sar-web-553x458.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Ensalada Caprese', 'Ensalada italiana de san pelegrino resaltada por rodajas de tomate y el sabor de la albahaca fresca.', 4500, 10, 1, 1, 'https://i.blogs.es/5ca73e/ensalada-caprese-rehacer-pakus-dap/1366_2000.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Ensalada Pescado', 'Ensalada con cuadritos de pan tostado con nuestro empanizado, al ajillo o grill', 4500, 10, 1, 1, 'https://www.recetasnestle.com.do/sites/default/files/srh_recipes/47b45c7192d1d88acff53e7064202d4f.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Sandwich de Pollo', 'Con pan ciabatta, nuestro sándwich de pollo, lechuga, tomate y deliciosas salsa clásicas', 3700, 10, 2, 1, 'https://images.aws.nestle.recipes/original/0dcdbe631b092077fd7e411236c4b06d_sandwich_de_pollo_a_las_finas_hierbas_-_mx_ponte_bien.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Sandwich de Jamón y Queso', 'Deliciosa crepa de pollo en su salsa blanca', 3200, 10, 2, 1, 'https://www.comedera.com/wp-content/uploads/2021/03/sandwich-de-jamon-y-queso.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Sandwich de Carne', 'Con pan ciabatta, nuestro sándwich de jamón y queso, lechuga, tomate y deliciosas salsa clásicas.', 4000, 10, 2, 1, 'https://www.gourmet.cl/wp-content/uploads/2016/05/Sandwich-de-Carne-Mechada-con-cebolla-caramelizada-y-tomates-asados.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Sopa Azteca', 'La sopa de tomate por excelencia traída directo de México por papá.', 4000, 10, 3, 1, 'https://cdn0.recetasgratis.net/es/posts/6/0/5/sopa_azteca_35506_600_square.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Sopa de Mariscos', 'Compuesta por mariscos frescos, y el toque esencial de papá.', 4500, 10, 3, 1, 'https://www.comedera.com/wp-content/uploads/2018/03/sopa-de-marisco.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Sopa de Pollo', 'Para sacarnos de cualquier apuro, la sopa curativa clásica.', 3300, 10, 3, 1, 'https://especiasmontero.com/wp-content/uploads/2018/02/CaldoDePollo-1.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Sopa de Rabo', 'Sacando lo mejor de los ingredientes traemos la sopa preferida de papá.', 4000, 10, 3, 1, 'https://rumbameats.com/wp-content/uploads/2019/07/Hervido-de-_rabo-by-enrilemoine-7.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Sopa de Mondongo', 'Sopa tradicional de la tierra costarricense para un antojo de antaño.', 3500, 10, 3, 1, 'https://recetasdemicolombia.com/wp-content/uploads/2020/08/mondongo-500x375.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Wrap de Pollo y Bacon', 'Wrap relleno de pollo empanizado, delicioso tocino y nuestra salsa mayonesa chipotle.', 3500, 10, 4, 1, 'https://i.pinimg.com/736x/72/86/1b/72861baeaccca244bf2fee091a7dc675.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Wrap corvina', 'Wrap con pescado empanizado y nuestra clásica salsa tártara.', 3500, 10, 4, 1, 'https://i.pinimg.com/736x/f5/f7/9a/f5f79aa520c59e342d7c08a8fe3e9174.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Quesadilla Crepe', 'Deliciosa crepa de pollo en su sala blanca.', 3500, 10, 5, 1, 'https://thasneen.com/cooking/wp-content/uploads/2017/06/Indian-style-Quesadilla.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Quesadillas de Pollo o Carne', 'Con dos quesos, mozzarella y cheddar, disfrútalas como quieras!', 3700, 10, 5, 1, 'https://i.ytimg.com/vi/7J5JqSOP-1s/maxresdefault.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Quesadillas mixtas', 'Mezcla de los dos mundos, pollo y carne en uno solo.', 4000, 10, 5, 1, 'https://assets.unileversolutions.com/recipes-v2/231998.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Casados', 'Clásico plato que todos los ticos reconocemos, salvador de tandas, escoge entre mechada, pescado, pollo, chuleta o bistec.', 3500, 10, 6, 1, 'https://upload.wikimedia.org/wikipedia/commons/0/08/Casado_costarricense.png');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Chifrijo', 'Para los amantes de la combinación del chicharrón, frijoles y arroz, servido con el clásico oro verde y tortillitas para que amarre.', 3500, 10, 6, 1, 'https://okdiario.com/img/2020/05/07/receta-de-costa-rica_-chifrijo-1.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Chicharrones', 'El sabor de Puriscal hasta tu mesa, servido con yuca frita y ensalada a lo tico.', 3800, 10, 6, 1, 'https://www.cocinatis.com/archivos/202308/ctis1012-receta-chicharrones-de-cerdo-andaluces-1280x720x80xX.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Lengua en Salsa', 'Atrévete a probar nuestra suave lengua en salsa de tomate, calla hasta los más bocones con su sabor.', 4800, 10, 6, 1, 'https://www.recetascostarica.com/base/stock/Recipe/272-image/272-image_web.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Patitas de Cerdo', 'Patitas de cerdo con frijolitos blancos, plato lleno de puro sabor donde mi tata.', 4000, 10, 6, 1, 'https://www.nutricienta.com/imagenes/alimentos/alimento-nutricienta-manitas-de-cerdo.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Patacones', 'Perfecto para quitarse esas ganas de comer a lo tico, nuestros patacones vienen con carne mechada, frijoles molidos y pico de gallo.', 3700, 10, 6, 1, 'https://www.semana.com/resizer/D-Lcez1Rj4bSIUHKyMk9rwDRIMY=/1280x720/smart/filters:format(jpg):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/semana/CUVSFJ3V5ZEWVLBJ76BASDV2PY.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Rice and Beans', 'Limón presente en el menú de papá, pollo en salsa caribeña con ensalada y maduros con el inigualable rice and beans.', 4500, 10, 6, 1, 'https://www.allrecipes.com/thmb/YywjEMDfUzEtxUR_8i_B_4dd-7o=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/211325-b6b1befbb1644f9b93e66eee74dbe07f.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Chilli Relleno', 'Relleno de carne molida, un excelente plato para el buen tico.', 4200, 10, 6, 1, 'https://www.jennieo.com/wp-content/uploads/2019/11/image-recipe_turkey-and-spinach-chile-relleno-with-fresh-tomato-sauce.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Arroz con Carne', 'Arroz directo de la casa compuesto por una combinación perfecta de arroz y carne.', 4000, 10, 7, 1, 'https://recetacubana.com/wp-content/uploads/2019/12/receta-Arroz-con-Carne-de-Cerdo.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Arroz con Pollo', 'Arroz con el pollo desmechado clásico, haciendo de este un plato típico delicioso.', 3700, 10, 7, 1, 'https://img.bekiacocina.com/cocina/0000/179-h.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Arroz con Marinera', 'Elaborado con los mariscos más frescos seleccionados por papá.', 4500, 10, 7, 1, 'https://www.elespectador.com/resizer/iSDLgK_Xt86uhsXCmvAN_Jp0Elk=/1200x675/filters:quality(60):format(jpeg)/cloudfront-us-east-1.images.arcpublishing.com/elespectador/QT2HQD77JJGDTIYXU4COEHGIRE.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Arroz con Camarones', 'Arroz con camarones de alta calidad para saciar los paladares hambrientos.', 4500, 10, 7, 1, 'https://www.recetasnestle.com.ec/sites/default/files/srh_recipes/b5761ed0a862a8c3ae9980304cd22ded.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Pomodoro', 'Nuestra pasta en salsa de tomate con delicioso queso mozzarella.', 3500, 10, 9, 1, 'https://supermancooks.com/wp-content/uploads/2023/03/pasta-pomodoro-featured.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Bolognese', 'Deliciosa pasta con queso mozzarella, salsa de tomate y carne molida.', 3800, 10, 9, 1, 'https://feelgoodfoodie.net/wp-content/uploads/2023/04/Pasta-Bolognese-TIMG.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Marinera', 'Salsa de tomate o salsa blanca con mariscos o solo camarones.', 4500, 10, 9, 1, 'https://newmansown.com/wp-content/uploads/2022/03/shrimp-marinara-with-pasta.png');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Alfredo', 'Pasta con jamón y hongos en salsa blanca.', 4000, 10, 9, 1, 'https://images.aws.nestle.recipes/resized/cc72869fabfc2bdfa036fd1fe0e2bad8_creamy_alfredo_pasta_long_left_1080_850.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Filet de Corvina', 'Filet de corvina al grill, al ajillo o empanizado.', 4800, 10, 8, 1, 'https://pronacatqma.com/images/com_yoorecipe/banner_superior/8264_1.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Corvina Entera', 'Nuestra especial corvina entera sin espinas lista para ti.', 6700, 10, 8, 1, 'https://canalcocina.es/medias/images/1101_CocContigo_CorvinaHorno.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Pargo Entero', 'Pargo entero fresco para los que quieran recordar los días de playa.', 5800, 10, 8, 1, 'https://d1uz88p17r663j.cloudfront.net/original/cd153cfbb9d153b1786c7d45adac52b2_Pargo-rojo-al-sarten.png');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Corvina Entera a la Caribeña', 'Nuestra especial corvina entera acompañada de salsa caribeña y camarones.', 8700, 10, 8, 1, 'https://media-cdn.tripadvisor.com/media/photo-s/18/2f/ec/5f/corvina-entera-frita.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Camarones', 'Jugosos camarones empanizados o al ajillo para los fanáticos del mar.', 4700, 10, 8, 1, 'https://cloudfront-us-east-1.images.arcpublishing.com/elespectador/WFY4CMXRGZD3TA2FXSRPU7UDOA.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Mariscada', 'Mix de mariscos frescos cocinados al ajillo creando un platillo colorido.', 4500, 10, 8, 1, 'https://imag.bonviveur.com/mariscada-gallega.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Mejillones', 'Mejillones noruegos al ajillo seleccionados por papá.', 4800, 10, 8, 1, 'https://coyomar.es/wp-content/uploads/2022/06/Como-cocer-mejillones-1024x768.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Pollo al Grill', 'Nuestro especial pollo, tratado por la mano de nuestros chefs, a la parrilla.', 4000, 10, 10, 1, 'https://storage.googleapis.com/fitia-api-bucket/media/images/recipe_images/1006680.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Pollo a la Jalapeña', 'Pollo parrillero con ganas de más fuego, bañado en nuestra salsa especial de jalapeños.', 4500, 10, 10, 1, 'https://i.ytimg.com/vi/ChLkloORDfU/maxresdefault.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Pollo Cordon Bleu', 'Nuestro pollo en un platillo fabuloso, cordon bleu bañado en salsa blanca.', 4000, 10, 10, 1, 'https://i.ytimg.com/vi/i2fwv6beoT8/maxresdefault.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Hamburguesa Donde Papá', 'Exquisita hamburguesa de papá, pulled pork BBQ, pepinillos, bacon, aros de cebolla.', 4800, 10, 11, 1, 'https://delination.com/wp-content/uploads/2022/11/Hamburguesa-casera-de-res-con-papas-850x550.jpeg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Hamburguesa de Pollo', 'Una de las mejores hamburguesas para los fans del pollo a la parrilla.', 4500, 10, 11, 1, 'https://www.comedera.com/wp-content/uploads/2023/07/Hamburguesa-de-pollo-picante.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Hamburguesa con Queso', 'Hamburguesa con queso de papá, para saborear a gusto.', 3500, 10, 11, 1, 'https://pronacatqma.com/images/com_yoorecipe/banner_superior/18096_1.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Hamburguesa de Pescado', 'Hamburguesa de pescado con salsa tártara, lechuga y queso amarillo, solo... donde papá.', 4200, 10, 11, 1, 'https://editorialtelevisa.brightspotcdn.com/wp-content/uploads/2020/03/recetas-con-filete-de-pescado-fa%25CC%2581ciles-hamburguesa.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Costillas', 'Costilla de cerdo cocinada especialmente 3 horas por nuestros chefs.', 4800, 10, 14, 1, 'https://t1.uc.ltmcdn.com/es/posts/3/9/5/como_hacer_costillas_bbq_en_sarten_50593_orig.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Churrasco', 'Este delicioso corte proviene de la falda de la res, cortado transversalmente, tratado por papá.', 5800, 10, 12, 1, 'https://cdn0.recetasgratis.net/es/posts/2/3/1/churrasco_a_lo_pobre_77132_orig.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Churrasco a la Jalapeña', 'Churrasco en nuestra salsa especial a la jalapeña para darle su perfecto toque picante.', 6500, 10, 12, 1, 'https://media-cdn.tripadvisor.com/media/photo-m/1280/29/75/59/9e/churrasco-tipico.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Lomito', 'Destacado por su suavidad natural, este corte de características jugosas puede saciar a cualquiera.', 6200, 10, 12, 1, 'https://www.clarin.com/2021/07/26/u-aUfp64d_1200x0__1.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Lomito a la jalapeña', 'Para aquellos que quieran probar la parrilla de papá, el suave lomito en combinación con nuestro toque a la jalapeña.', 6800, 10, 12, 1, 'https://media-cdn.tripadvisor.com/media/photo-s/11/0c/bc/c4/puntas-de-lomito-a-la.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Puré', 'Suave y cremoso puré de papas, hecho con papas seleccionadas y un toque de mantequilla, ideal para complementar cualquier plato principal. Servido caliente', 1000, 10, 13, 1, 'https://images.aws.nestle.recipes/original/892d65cba81876ed7c340ae9ce7663d3_DCS_MARZO_INSTAGRAM-04.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Vegetales', 'Mix de vegetales de temporada, cocidos al vapor para preservar su frescura y sabor natural. Una opción saludable y colorida.', 1000, 10, 13, 1, 'https://cdn.aarp.net/content/aarpe/es/home/salud/vida-saludable/info-2023/comer-vegetales-verduras-crudos-o-cocidos/_jcr_content/root/container_main/container_body_main/container_body1/container_body_cf/container_image/articlecontentfragment/cfimage.coreimg.50.932.jpeg/content/dam/aarp/health/healthy-living/2023/07/1140-colorfulrawveggies-esp.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Papas asadas', 'Papas asadas hasta lograr una piel crujiente y un interior suave, sazonadas con hierbas finas y un toque de aceite de oliva.', 1000, 10, 13, 1, 'https://www.gourmet.cl/wp-content/uploads/2014/09/Papas-Asadas.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Arroz', 'Arroz blanco esponjoso, cocido a la perfección, un básico indispensable para acompañar una variedad de platos.', 1000, 10, 13, 1, 'https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/05bab5cb-f8b6-487d-a509-f38031ea2708/Derivates/142b07d0-cedc-44f8-8569-e0222afab308.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Papas fritas', 'Papas fritas doradas y crujientes, cortadas a mano y fritas en aceite de alta calidad, con un toque de sal marina para realzar su sabor.', 1000, 10, 13, 1, 'https://phantom-marca.unidadeditorial.es/813d16708dc72860fd3cf319c9a245b5/resize/828/f/jpg/assets/multimedia/imagenes/2023/08/04/16911461030527.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Yuca Frita', 'Yuqitas a lo tico, fritas apenas para un gusto.', 1800, 10, 15, 1, 'https://mexicanappetizersandmore.com/wp-content/uploads/Yuca-Frita-1-12.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Patacones', 'Patacones clásicos con frijoles molidos y pico de gallo.', 1800, 10, 15, 1, 'https://images.hola.com/imagenes/cocina/recetas/20200320163599/receta-patacones-platano/0-800-862/patacones-adobe-m.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Aros de Cebolla', 'Aros de cebolla crujientes por fuera y por dentro!', 2200, 10, 15, 1, 'https://images.hola.com/imagenes/cocina/recetas/20220209204312/aros-cebolla-crujientes/1-49-243/aros-cebolla-adobe-t.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Papas Gajo', 'El estilo de papas favoritas de papá, pide las que quieres.', 2200, 10, 15, 1, 'https://www.paulinacocina.net/wp-content/uploads/2023/11/receta-de-papas-gajo-Paulina-Cocina-Recetas.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Papas Francesas', 'Papas fritas apenas para acompañar tu comida.', 1800, 10, 15, 1, 'https://www.paulinacocina.net/wp-content/uploads/2015/08/P1140112-e1439267676931.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Palitos de Queso', 'Palitos de queso mozzarella, de la mejor compañía que puedas tener.', 2200, 10, 15, 1, 'https://mandolina.co/wp-content/uploads/2023/06/deditos-de-queso-1200x900.png');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Gallos de salchichón', 'Deliciosos gallos de salchichón.', 2000, 10, 17, 1, 'https://tortiricascentroamerica.com/wp-content/uploads/2016/01/receta-tortiricas-gallitos-faciles.png');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Gallos de Chorizo', 'Deliciosos gallos de chorizo.', 2000, 10, 17, 1, 'https://cloudfront-us-east-1.images.arcpublishing.com/gruponacion/QZ7BD6VNOVFFPDH7VAWWQTRFTY.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Tacos', 'Deliciosos tacos.', 2000, 10, 17, 1, 'https://www.comedera.com/wp-content/uploads/2017/08/tacos-al-pastor-receta.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES ('Tacos de Camaron', 'Deliciosos tacos de camaron.', 2700, 10, 17, 1, 'https://t2.uc.ltmcdn.com/es/posts/2/8/1/como_hacer_tacos_de_camaron_enchilado_51182_orig.jpg');



//RESERVACION
-- Inserts en la tabla reservacion
INSERT INTO usuarioDondePapa.reservacion (nombre, hora, numero_de_mesa, contacto) 
VALUES ('Juan', TO_TIMESTAMP('02:30:00 PM', 'HH12:MI:SSXFF AM'), 1, '88269654');
INSERT INTO usuarioDondePapa.reservacion (nombre, hora, numero_de_mesa, contacto) 
VALUES ('María', TO_TIMESTAMP('01:00:00 PM', 'HH12:MI:SSXFF AM'), 2, '84811690');
INSERT INTO usuarioDondePapa.reservacion (nombre, hora, numero_de_mesa, contacto) 
VALUES ('Jose', TO_TIMESTAMP('08:00:00 PM', 'HH12:MI:SSXFF AM'), 3, '22656504');



//USUARIO
-- Inserts en la tabla usuario
INSERT INTO usuarioDondePapa.usuario (username, password, nombre, apellidos, correo, telefono, ruta_imagen, activo) VALUES ('juan', '$2a$12$RnK02njwwqKfsnWd1C8bAOfOsXQIZZbYkCbCkobm1ohrIYLqp2wTS', 'Juan', 'Castro Mora', 'jcastro@gmail.com', '4556-8978', 'https://img.freepik.com/foto-gratis/chico-guapo-seguro-posando-contra-pared-blanca_176420-32936.jpg', 1);
INSERT INTO usuarioDondePapa.usuario (username, password, nombre, apellidos, correo, telefono, ruta_imagen, activo) VALUES ('lafit', '$2a$12$ufVcPe2JbuMo0yCCRj5nue.bmAlwEzlelGqgOp/p8eZL6Q3qgNxU6', 'Chuty', 'Villalobos', 'chutyvillalobos@gmail.com', '5456-8789', 'https://pbs.twimg.com/media/EahiQBxX0AEud1m.jpg', 1);
INSERT INTO usuarioDondePapa.usuario (username, password, nombre, apellidos, correo, telefono, ruta_imagen, activo) VALUES ('allan', '$2a$12$vtCj3aCfKG58ZmS8ZGE3CuQgydCDeb6XuF1vAKIGPDos58eoYA3Im', 'Allan', 'Allan Loria', 'allanlafit@gmail.com', '7898-8936', 'https://www.diarioextra.com/files/Dnews/images/detail/500526_allanvillalobos.jpg', 1);

//ROL
-- Inserts en la tabla rol
INSERT INTO usuarioDondePapa.rol (nombre, id_usuario) VALUES ('ROLE_ADMIN', 1);
INSERT INTO usuarioDondePapa.rol (nombre, id_usuario) VALUES ('ROLE_VENDEDOR', 2);
INSERT INTO usuarioDondePapa.rol (nombre, id_usuario) VALUES ('ROLE_USER', 3);

//FACTURA
-- Inserts en la tabla factura
INSERT INTO usuarioDondePapa.factura (id_usuario, fecha, total, estado) VALUES (1, TO_DATE('2024-01-05', 'YYYY-MM-DD'), 211560, 2);
INSERT INTO usuarioDondePapa.factura (id_usuario, fecha, total, estado) VALUES (2, TO_DATE('2024-01-07', 'YYYY-MM-DD'), 554340, 2);
INSERT INTO usuarioDondePapa.factura (id_usuario, fecha, total, estado) VALUES (3, TO_DATE('2024-01-07', 'YYYY-MM-DD'), 871000, 2);
INSERT INTO usuarioDondePapa.factura (id_usuario, fecha, total, estado) VALUES (1, TO_DATE('2024-01-15', 'YYYY-MM-DD'), 244140, 1);
INSERT INTO usuarioDondePapa.factura (id_usuario, fecha, total, estado) VALUES (2, TO_DATE('2024-01-17', 'YYYY-MM-DD'), 414800, 1);
INSERT INTO usuarioDondePapa.factura (id_usuario, fecha, total, estado) VALUES (3, TO_DATE('2024-01-21', 'YYYY-MM-DD'), 420000, 1);

//VENTA
-- Inserts en la tabla venta
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES (1, 5, 45000, 3);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES (2, 9, 15780, 2);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES (3, 10, 15000, 3);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES (1, 2, 45000, 1);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES (2, 14, 154000, 3);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES (2, 9, 15780, 3);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES (3, 14, 154000, 1);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES (3, 6, 57000, 1);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES (3, 15, 330000, 2);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES (1, 6, 57000, 2);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES (1, 8, 27600, 3);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES (1, 9, 15780, 3);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES (2, 8, 27600, 3);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES (2, 14, 154000, 2);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES (2, 3, 24000, 1);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES (3, 15, 330000, 1);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES (3, 12, 45000, 1);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES (3, 10, 15000, 3);
COMMIT;

--------------------------------------------------------
-- PROCEDIMIENTOS ALMACENADOS
--------------------------------------------------------
SET SERVEROUTPUT ON;

// 1. Procedimiento para obtener los platos disponibles
CREATE OR REPLACE PROCEDURE OBTENER_PLATOS_DISPONIBLES 
AS
BEGIN
    FOR platos_disponibles IN (SELECT descripcion FROM usuarioDondePapa.plato WHERE disponible = 1) LOOP
        DBMS_OUTPUT.PUT_LINE('Plato: ' || platos_disponibles.descripcion);
    END LOOP; 
END;

EXEC OBTENER_PLATOS_DISPONIBLES;

--------------------------------------------------------

// 2. Procedimiento para calcular el total de una factura
CREATE OR REPLACE PROCEDURE CALCULAR_TOTAL_FACTURA (
    id_factura IN NUMBER,
    total OUT NUMBER
) 
AS
BEGIN
    SELECT SUM(precio * cantidad) INTO total
    FROM usuarioDondePapa.venta
    WHERE id_factura = id_factura;
END;


DECLARE
    total NUMBER;
BEGIN
    CALCULAR_TOTAL_FACTURA(1, total);
    DBMS_OUTPUT.PUT_LINE('Total de la factura: ' || total);
END;

--------------------------------------------------------

-- 3. Procedimiento para obtener facturas por usuario
CREATE OR REPLACE PROCEDURE OBTENER_FACTURAS_POR_USUARIO (
    id_usuario IN NUMBER
) 
AS
BEGIN
    FOR facturas IN (SELECT * FROM usuarioDondePapa.factura WHERE id_usuario = id_usuario) LOOP
        DBMS_OUTPUT.PUT_LINE('ID Factura: ' || facturas.id_factura || ', Fecha: ' || facturas.fecha || ', Total: ' || facturas.total || ', Estado: ' || facturas.estado);
    END LOOP;
END;

EXEC OBTENER_FACTURAS_POR_USUARIO(1);

--------------------------------------------------------

-- 4. Procedimiento para insertar nueva categoria
CREATE OR REPLACE PROCEDURE INSERTAR_CATEGORIA (
    descripcion IN VARCHAR2,
    disponible IN NUMBER,
    ruta_imagen IN VARCHAR2
) 
AS
BEGIN
    INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen)
    VALUES (descripcion, disponible, ruta_imagen);
END;


BEGIN
    INSERTAR_CATEGORIA('Bebidas', 1, 'ruta/a/imagen');
END;

--------------------------------------------------------

// 5. Procedimiento para obtener ventas por plato
CREATE OR REPLACE PROCEDURE OBTENER_VENTAS_POR_PLATO (
    id_plato IN NUMBER
) 
AS
BEGIN
    FOR ventas IN (SELECT * FROM usuarioDondePapa.venta WHERE id_plato = id_plato) LOOP
        DBMS_OUTPUT.PUT_LINE('ID Venta: ' || ventas.id_venta || ', ID Factura: ' || ventas.id_factura || ', Precio: ' || ventas.precio || ', Cantidad: ' || ventas.cantidad);
    END LOOP;
END;

EXEC OBTENER_VENTAS_POR_PLATO(1);

--------------------------------------------------------

// 6. Procedimiento para insertar un nuevo plato
CREATE OR REPLACE PROCEDURE INSERTAR_PLATO (
    id_categoria IN NUMBER,
    descripcion IN VARCHAR2,
    detalle IN VARCHAR2,
    precio IN NUMBER,
    existencias IN NUMBER,
    ruta_imagen IN VARCHAR2,
    disponible IN NUMBER
) 
AS
BEGIN
    INSERT INTO usuarioDondePapa.plato (id_categoria, descripcion, detalle, precio, existencias, ruta_imagen, disponible)
    VALUES (id_categoria, descripcion, detalle, precio, existencias, ruta_imagen, disponible);
END;

BEGIN
    INSERTAR_PLATO(1, 'Plato Ejemplo', 'Detalle del Plato', 100, 10, 'ruta/a/imagen', 1);
END;

--------------------------------------------------------

// 7. Procedimiento para actualizar categoria
CREATE OR REPLACE PROCEDURE ACTUALIZAR_CATEGORIA (
    id_categoria IN NUMBER,
    descripcion IN VARCHAR2,
    disponible IN NUMBER,
    ruta_imagen IN VARCHAR2
) 
AS
BEGIN
    UPDATE usuarioDondePapa.categoria
    SET descripcion = descripcion,
        disponible = disponible,
        ruta_imagen = ruta_imagen
    WHERE id_categoria = id_categoria;
END;


BEGIN
    ACTUALIZAR_CATEGORIA(1, 'Bebidas Actualizadas', 1, 'ruta/a/nueva/imagen');
END;

--------------------------------------------------------

// 8. Procedimiento para eliminar una reservacion
CREATE OR REPLACE PROCEDURE ELIMINAR_RESERVACION (
    p_id_reservacion IN NUMBER
) 
AS
BEGIN
    DELETE FROM usuarioDondePapa.reservacion
    WHERE id_reservacion = p_id_reservacion;
END;
/




BEGIN
    ELIMINAR_RESERVACION(1);
END;

--------------------------------------------------------

// 9. Procedimiento para insertar nuevo plato
CREATE OR REPLACE PROCEDURE INSERTAR_NUEVO_PLATO (
    id_categoria IN NUMBER,
    descripcion IN VARCHAR2,
    detalle IN VARCHAR2,
    precio IN NUMBER,
    existencias IN NUMBER,
    ruta_imagen IN VARCHAR2,
    disponible IN NUMBER
) 
AS
BEGIN
    INSERT INTO usuarioDondePapa.plato (id_categoria, descripcion, detalle, precio, existencias, ruta_imagen, disponible)
    VALUES (id_categoria, descripcion, detalle, precio, existencias, ruta_imagen, disponible);
END;

BEGIN
    INSERTAR_NUEVO_PLATO(1, 'Otro Plato Ejemplo', 'Otro Detalle del Plato', 120, 20, 'ruta/a/otra/imagen', 1);
END;

--------------------------------------------------------

// 10. Procedimiento para eliminar un plato 
CREATE OR REPLACE PROCEDURE ELIMINAR_PLATO (
    p_id_plato IN NUMBER
) 
AS
BEGIN
    -- Primero, eliminar las referencias en la tabla ventas
    DELETE FROM usuarioDondePapa.venta
    WHERE id_plato = p_id_plato;

    -- Luego, eliminar el plato en la tabla plato
    DELETE FROM usuarioDondePapa.plato
    WHERE id_plato = p_id_plato;
END;
/



BEGIN
    ELIMINAR_PLATO(55);
END;

--------------------------------------------------------

// 11. Procedimiento para obtener el total de ventas por usuario
CREATE OR REPLACE PROCEDURE OBTENER_TOTAL_VENTAS_POR_USUARIO (
    id_usuario IN NUMBER
) 
AS
BEGIN
    FOR ventas IN (SELECT f.id_usuario, SUM(v.precio * v.cantidad) AS total_ventas
                   FROM usuarioDondePapa.venta v
                   JOIN usuarioDondePapa.factura f ON v.id_factura = f.id_factura
                   WHERE f.id_usuario = id_usuario
                   GROUP BY f.id_usuario) LOOP
        DBMS_OUTPUT.PUT_LINE('ID Usuario: ' || ventas.id_usuario || ', Total Ventas: ' || ventas.total_ventas);
    END LOOP;
END;

EXEC OBTENER_TOTAL_VENTAS_POR_USUARIO(1);

--------------------------------------------------------

// 12. Procedimiento para modificar la disponibilidad de un plato
CREATE OR REPLACE PROCEDURE MODIFICAR_DISPONIBILIDAD_PLATO (
    id_plato IN NUMBER,
    disponible IN NUMBER
) 
AS
BEGIN
    UPDATE usuarioDondePapa.plato
    SET disponible = disponible
    WHERE id_plato = id_plato;
END;

BEGIN
    MODIFICAR_DISPONIBILIDAD_PLATO(1, 0);
END;


--------------------------------------------------------

// 13. Filtrar por precion superior y inferior.
CREATE OR REPLACE PROCEDURE FILTRAR_PLATOS_POR_PRECIO (
    p_precio_inf IN NUMBER,
    p_precio_sup IN NUMBER
) 
AS
BEGIN
    FOR r_plato IN (SELECT descripcion, precio 
                    FROM usuarioDondePapa.plato 
                    WHERE precio BETWEEN p_precio_inf AND p_precio_sup 
                    ORDER BY descripcion ASC) 
    LOOP
        DBMS_OUTPUT.PUT_LINE('Plato: ' || r_plato.descripcion || ', Precio: ' || r_plato.precio);
    END LOOP;
END;
/

BEGIN
    -- Prueba del procedimiento con un rango de precios
    FILTRAR_PLATOS_POR_PRECIO(1000, 5000);
END;
/
--------------------------------------------------------
--14. Procedimiento para actualizar el precio de un plato.

CREATE OR REPLACE PROCEDURE ACTUALIZAR_PRECIO_PLATO (
    p_id_plato IN NUMBER,
    p_nuevo_precio IN NUMBER
) 
AS
BEGIN
    UPDATE usuarioDondePapa.plato
    SET precio = p_nuevo_precio
    WHERE id_plato = p_id_plato;
END;

BEGIN
    -- Ejecuta el procedimiento para actualizar el precio de un plato específico
    ACTUALIZAR_PRECIO_PLATO(
        1,          -- ID del plato 
        1500      -- Nuevo precio que asignar al plato
    );
END;
/

SELECT * FROM usuarioDondePapa.plato WHERE id_plato = 1;

--------------------------------------------------------
--15. Procedimiento para obtener la lista de categorías disponibles
CREATE OR REPLACE PROCEDURE OBTENER_CATEGORIAS_DISPONIBLES 
AS
BEGIN
    FOR categorias IN (SELECT descripcion FROM usuarioDondePapa.categoria WHERE disponible = 1) LOOP
        DBMS_OUTPUT.PUT_LINE('Categoría: ' || categorias.descripcion);
    END LOOP;
END;

BEGIN
    -- Ejecuta el procedimiento para obtener las categorías disponibles
    OBTENER_CATEGORIAS_DISPONIBLES;
END;
/
--------------------------------------------------------
--16.  Procedimiento para contar el número de platos por categoría

CREATE OR REPLACE PROCEDURE CONTAR_PLATOS_POR_CATEGORIA 
AS
BEGIN
    FOR categoria IN (SELECT c.descripcion, COUNT(p.id_plato) AS numero_platos 
                      FROM usuarioDondePapa.categoria c
                      JOIN usuarioDondePapa.plato p ON c.id_categoria = p.id_categoria
                      GROUP BY c.descripcion) LOOP
        DBMS_OUTPUT.PUT_LINE('Categoría: ' || categoria.descripcion || ', Número de Platos: ' || categoria.numero_platos);
    END LOOP;
END;

BEGIN
    -- Ejecuta el procedimiento para contar los platos por categoría
    CONTAR_PLATOS_POR_CATEGORIA;
END;
/

--------------------------------------------------------
--17. Procedimiento para insertar un nuevo usuario

CREATE OR REPLACE PROCEDURE INSERTAR_USUARIO (
    p_username IN VARCHAR2,
    p_password IN VARCHAR2,
    p_nombre IN VARCHAR2,
    p_apellidos IN VARCHAR2,
    p_correo IN VARCHAR2,
    p_telefono IN VARCHAR2,
    p_ruta_imagen IN VARCHAR2,
    p_activo IN NUMBER
) 
AS
BEGIN
    INSERT INTO usuarioDondePapa.usuario (username, password, nombre, apellidos, correo, telefono, ruta_imagen, activo)
    VALUES (p_username, p_password, p_nombre, p_apellidos, p_correo, p_telefono, p_ruta_imagen, p_activo);
END;
/

BEGIN
    -- Prueba del procedimiento insertando un nuevo usuario
    INSERTAR_USUARIO(
        'jdoe',                 -- Username del usuario
        'password123',          -- Contraseña del usuario
        'John',                 -- Nombre del usuario
        'Doe',                  -- Apellidos del usuario
        'john.doe@email.com',   -- Correo electrónico del usuario
        '555-1234',             -- Teléfono del usuario
        '/images/jdoe.png',     -- imagen del usuario
        1                       -- Activo (1 = sí, 0 = no)
    );
END;
/


SELECT * FROM usuarioDondePapa.usuario WHERE username = 'jdoe';



BEGIN
    -- Prueba del procedimiento insertando un nuevo usuario
    INSERTAR_USUARIO(
        'Juan Perez',           -- Nombre del usuario
        'juan.perez@email.com', -- Correo electrónico del usuario
        '555-1234',             -- Teléfono del usuario
        'password123'           -- Contraseña del usuario
    );
END;
/

SELECT * FROM usuarioDondePapa.usuario WHERE correo = 'juan.perez@email.com';

--------------------------------------------------------
--17. Procedimiento para eliminar una factura.
CREATE OR REPLACE PROCEDURE ELIMINAR_FACTURA (
    p_id_factura IN NUMBER
) 
AS
BEGIN
    -- Eliminar las ventas asociadas a la factura
    DELETE FROM usuarioDondePapa.venta
    WHERE id_factura = p_id_factura;

    -- Eliminar la factura
    DELETE FROM usuarioDondePapa.factura
    WHERE id_factura = p_id_factura;
END;

BEGIN
    -- Prueba del procedimiento eliminando una factura específica
    ELIMINAR_FACTURA(1); 
END;
/

--------------------------------------------------------
-- VISTAS
--------------------------------------------------------

// 1. Mostrar todos los platos disponibles por categoria a la que pertencen
CREATE OR REPLACE VIEW usuarioDondePapa.vista_platos_disponibles AS
SELECT 
    p.id_plato,
    p.descripcion AS plato_descripcion,
    p.detalle,
    p.precio,
    p.existencias,
    p.ruta_imagen,
    c.descripcion AS categoria_descripcion,
    p.disponible
FROM 
    usuarioDondePapa.plato p
JOIN 
    usuarioDondePapa.categoria c ON p.id_categoria = c.id_categoria
WHERE 
    p.disponible = 1;
    
--------------------------------------------------------

// 2. Muestra informacion adicional sobre los usuarios que las realizaron.informaci?n adicional sobre los usuarios que las realizaron.
CREATE OR REPLACE VIEW usuarioDondePapa.vista_facturas_con_usuarios AS
SELECT 
    f.id_factura,
    f.fecha,
    f.total,
    f.estado,
    u.nombre,
    u.apellidos,
    u.correo,
    u.telefono
FROM 
    usuarioDondePapa.factura f
JOIN 
    usuarioDondePapa.usuario u ON f.id_usuario = u.id_usuario;
    
--------------------------------------------------------
    
// 3. Esta vista muestra las ventas realizadas, incluyendo informaci?n del plato vendido y la factura asociada.
CREATE OR REPLACE VIEW usuarioDondePapa.vista_ventas_detalles AS
SELECT 
    v.id_venta,
    f.fecha,
    p.descripcion AS plato_descripcion,
    p.precio,
    v.cantidad,
    v.precio AS precio_venta,
    f.total AS total_factura
FROM 
    usuarioDondePapa.venta v
JOIN 
    usuarioDondePapa.factura f ON v.id_factura = f.id_factura
JOIN 
    usuarioDondePapa.plato p ON v.id_plato = p.id_plato;

--------------------------------------------------------

// 4. Esta vista muestra los usuarios junto con los roles asignados a cada uno.
CREATE OR REPLACE VIEW usuarioDondePapa.vista_usuarios_roles AS
SELECT 
    u.id_usuario,
    u.username,
    u.nombre,
    u.apellidos,
    r.nombre AS rol
FROM 
    usuarioDondePapa.usuario u
JOIN 
    usuarioDondePapa.rol r ON u.id_usuario = r.id_usuario;

--------------------------------------------------------

// 5. Esta vista muestra todas las reservaciones con informaci?n de contacto.
CREATE OR REPLACE VIEW usuarioDondePapa.vista_reservaciones AS
SELECT 
    r.id_reservacion,
    r.nombre,
    r.hora,
    r.numero_de_mesa,
    r.contacto
FROM 
    usuarioDondePapa.reservacion r;
--------------------------------------------------------
// 6. Esta vista muestra los ingresos diarios del restaurante, agrupados por fecha.

CREATE OR REPLACE VIEW usuarioDondePapa.vista_ingresos_diarios AS
SELECT 
    TO_CHAR(f.fecha, 'YYYY-MM-DD') AS fecha,
    SUM(f.total) AS total_ingresos
FROM 
    usuarioDondePapa.factura f
GROUP BY 
    TO_CHAR(f.fecha, 'YYYY-MM-DD')
ORDER BY 
    fecha DESC;


--------------------------------------------------------
//  7. Esta vista muestra los platos más vendidos, ordenados por la cantidad vendida.

CREATE OR REPLACE VIEW usuarioDondePapa.vista_top_platos_vendidos AS
SELECT 
    p.id_plato,
    p.descripcion AS plato_descripcion,
    SUM(v.cantidad) AS total_vendido
FROM 
    usuarioDondePapa.venta v
JOIN 
    usuarioDondePapa.plato p ON v.id_plato = p.id_plato
GROUP BY 
    p.id_plato, p.descripcion
ORDER BY 
    total_vendido DESC;
--------------------------------------------------------
//8. Esta vista muestra a los clientes más frecuentes, ordenados por el número de facturas emitidas a su nombre.

CREATE OR REPLACE VIEW usuarioDondePapa.vista_clientes_frecuentes AS
SELECT 
    u.id_usuario,
    u.nombre,
    u.apellidos,
    COUNT(f.id_factura) AS total_facturas
FROM 
    usuarioDondePapa.usuario u
JOIN 
    usuarioDondePapa.factura f ON u.id_usuario = f.id_usuario
GROUP BY 
    u.id_usuario, u.nombre, u.apellidos
ORDER BY 
    total_facturas DESC;
--------------------------------------------------------
// 9. Esta vista muestra todos los productos (platos) que actualmente no tienen existencias disponibles.

CREATE OR REPLACE VIEW usuarioDondePapa.vista_productos_no_disponibles AS
SELECT 
    p.id_plato,
    p.descripcion AS plato_descripcion,
    p.detalle,
    p.precio,
    p.ruta_imagen,
    c.descripcion AS categoria_descripcion
FROM 
    usuarioDondePapa.plato p
JOIN 
    usuarioDondePapa.categoria c ON p.id_categoria = c.id_categoria
WHERE 
    p.existencias = 0 
    OR p.disponible = 0
ORDER BY 
    p.descripcion ASC;




--------------------------------------------------------
// 10. Esta vista muestra los usuarios que tienen facturas pendientes de pago.
CREATE OR REPLACE VIEW usuarioDondePapa.vista_categorias_mas_vendidas AS
SELECT 
    c.id_categoria,
    c.descripcion AS categoria_descripcion,
    SUM(v.cantidad) AS total_vendido,
    SUM(v.precio * v.cantidad) AS ingresos_generados
FROM 
    usuarioDondePapa.categoria c
JOIN 
    usuarioDondePapa.plato p ON c.id_categoria = p.id_categoria
JOIN 
    usuarioDondePapa.venta v ON p.id_plato = v.id_plato
GROUP BY 
    c.id_categoria, c.descripcion
ORDER BY 
    total_vendido DESC;


--------------------------------------------------------

--------------------------------------------------------
-- CURSORES
--------------------------------------------------------
--------------------------------------------------------
-- CURSORES
--------------------------------------------------------
SET SERVEROUTPUT ON;


// 1.
CREATE OR REPLACE PROCEDURE OBTENER_PLATOS_DISPONIBLES 
AS
    CURSOR platos_disponibles_cur IS
        SELECT descripcion FROM usuarioDondePapa.plato WHERE disponible = 1;
    v_descripcion usuarioDondePapa.plato.descripcion%TYPE;
BEGIN
    OPEN platos_disponibles_cur;
    LOOP
        FETCH platos_disponibles_cur INTO v_descripcion;
        EXIT WHEN platos_disponibles_cur%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('Plato: ' || v_descripcion);
    END LOOP;
    CLOSE platos_disponibles_cur;
END;

BEGIN
    OBTENER_PLATOS_DISPONIBLES;
END;
--------------------------------------------------------

// 2.
CREATE OR REPLACE PROCEDURE OBTENER_FACTURAS_POR_USUARIO (
    id_usuario IN NUMBER
) 
AS
    CURSOR facturas_cur IS
        SELECT * FROM usuarioDondePapa.factura WHERE id_usuario = id_usuario;
    v_factura usuarioDondePapa.factura%ROWTYPE;
BEGIN
    OPEN facturas_cur;
    LOOP
        FETCH facturas_cur INTO v_factura;
        EXIT WHEN facturas_cur%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Factura: ' || v_factura.id_factura || ', Fecha: ' || v_factura.fecha || ', Total: ' || v_factura.total || ', Estado: ' || v_factura.estado);
    END LOOP;
    CLOSE facturas_cur;
END;

BEGIN
    OBTENER_FACTURAS_POR_USUARIO(1);  -- ACA SE CAMBIA POR EL VALOR DE USER
END;
--------------------------------------------------------

// 3.
CREATE OR REPLACE PROCEDURE OBTENER_VENTAS_POR_PLATO (
    id_plato IN NUMBER
) 
AS
    CURSOR ventas_cur IS
        SELECT * FROM usuarioDondePapa.venta WHERE id_plato = id_plato;
    v_venta usuarioDondePapa.venta%ROWTYPE;
BEGIN
    OPEN ventas_cur;
    LOOP
        FETCH ventas_cur INTO v_venta;
        EXIT WHEN ventas_cur%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Venta: ' || v_venta.id_venta || ', ID Factura: ' || v_venta.id_factura || ', Precio: ' || v_venta.precio || ', Cantidad: ' || v_venta.cantidad);
    END LOOP;
    CLOSE ventas_cur;
END;

BEGIN
    OBTENER_VENTAS_POR_PLATO(2);  -- SE CAMBIA POR EL ID
END;

--------------------------------------------------------

// 4
CREATE OR REPLACE PROCEDURE OBTENER_TOTAL_VENTAS_POR_USUARIO (
    id_usuario IN NUMBER
) 
AS
    CURSOR ventas_total_cur IS
        SELECT f.id_usuario, SUM(v.precio * v.cantidad) AS total_ventas
        FROM usuarioDondePapa.venta v
        JOIN usuarioDondePapa.factura f ON v.id_factura = f.id_factura
        WHERE f.id_usuario = id_usuario
        GROUP BY f.id_usuario;
    v_id_usuario usuarioDondePapa.factura.id_usuario%TYPE;
    v_total_ventas NUMBER;
BEGIN
    OPEN ventas_total_cur;
    LOOP
        FETCH ventas_total_cur INTO v_id_usuario, v_total_ventas;
        EXIT WHEN ventas_total_cur%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Usuario: ' || v_id_usuario || ', Total Ventas: ' || v_total_ventas);
    END LOOP;
    CLOSE ventas_total_cur;
END;

BEGIN
    OBTENER_TOTAL_VENTAS_POR_USUARIO(1);  -- CAMBIAR POR USER
END;

--------------------------------------------------------

// 5.
CREATE OR REPLACE PROCEDURE OBTENER_RESERVACIONES (
    id_reservacion IN NUMBER
) 
AS
    CURSOR reservaciones_cur IS
        SELECT * FROM usuarioDondePapa.reservacion WHERE id_reservacion = id_reservacion;
    v_reservacion usuarioDondePapa.reservacion%ROWTYPE;
BEGIN
    OPEN reservaciones_cur;
    LOOP
        FETCH reservaciones_cur INTO v_reservacion;
        EXIT WHEN reservaciones_cur%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Reservacion: ' || v_reservacion.id_reservacion || ', Nombre: ' || v_reservacion.nombre || ', Hora: ' || v_reservacion.hora || ', Numero de Mesa: ' || v_reservacion.numero_de_mesa || ', Contacto: ' || v_reservacion.contacto);
    END LOOP;
    CLOSE reservaciones_cur;
END;

BEGIN
    OBTENER_RESERVACIONES(101);  -- CAMBIAR POR ID RESERVACION
END;

--------------------------------------------------------

// 6.
CREATE OR REPLACE PROCEDURE OBTENER_CLIENTES_POR_ESTADO (
    estado IN NUMBER
) 
AS
    CURSOR clientes_cursor IS
        SELECT ID_USUARIO, NOMBRE, CORREO
        FROM USUARIODONDEPAPA.USUARIO
        WHERE ACTIVO = estado;
    
    cliente_record clientes_cursor%ROWTYPE;
BEGIN
    OPEN clientes_cursor;
    LOOP
        FETCH clientes_cursor INTO cliente_record;
        EXIT WHEN clientes_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Usuario: ' || cliente_record.ID_USUARIO || ', Nombre: ' || cliente_record.NOMBRE || ', Correo: ' || cliente_record.CORREO);
    END LOOP;
    CLOSE clientes_cursor;
END;

BEGIN
    OBTENER_CLIENTES_POR_ESTADO(1);  -- CAMBIAR POR EL ESTADO
END;

--------------------------------------------------------

// 7.
CREATE OR REPLACE PROCEDURE OBTENER_PRODUCTOS_POR_CATEGORIA (
    id_categoria IN NUMBER
) 
AS
    CURSOR productos_cursor IS
        SELECT ID_PLATO, DESCRIPCION, PRECIO
        FROM USUARIODONDEPAPA.PLATO
        WHERE ID_CATEGORIA = id_categoria;
    
    producto_record productos_cursor%ROWTYPE;
BEGIN
    OPEN productos_cursor;
    LOOP
        FETCH productos_cursor INTO producto_record;
        EXIT WHEN productos_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Plato: ' || producto_record.ID_PLATO || ', DescripciÃ³n: ' || producto_record.DESCRIPCION || ', Precio: ' || producto_record.PRECIO);
    END LOOP;
    CLOSE productos_cursor;
END;

BEGIN
    OBTENER_PRODUCTOS_POR_CATEGORIA(2);  -- CAMBIAR ID POR CATEGORIA
END;

--------------------------------------------------------
// 8.
CREATE OR REPLACE PROCEDURE OBTENER_RESERVAS_POR_FECHA (
    fecha IN DATE
) 
AS
    CURSOR reservas_cursor IS
        SELECT ID_RESERVACION, NOMBRE, HORA, NUMERO_DE_MESA
        FROM USUARIODONDEPAPA.RESERVACION
        WHERE TRUNC(HORA) = fecha;
    
    reserva_record reservas_cursor%ROWTYPE;
BEGIN
    OPEN reservas_cursor;
    LOOP
        FETCH reservas_cursor INTO reserva_record;
        EXIT WHEN reservas_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Reserva: ' || reserva_record.ID_RESERVACION || ', Nombre: ' || reserva_record.NOMBRE || ', Hora: ' || reserva_record.HORA || ', Número de Mesa: ' || reserva_record.NUMERO_DE_MESA);
    END LOOP;
    CLOSE reservas_cursor;
END;

BEGIN
    OBTENER_RESERVAS_POR_FECHA(TO_DATE('2024-08-21', 'YYYY-MM-DD')); -- CAMBIAR FECHA DEFAUL
END;

--------------------------------------------------------
//9.
CREATE OR REPLACE PROCEDURE OBTENER_VENTAS_POR_FECHA (
    fecha IN DATE
) 
AS
    CURSOR ventas_cursor IS
        SELECT ID_VENTA, ID_PLATO, CANTIDAD, PRECIO
        FROM USUARIODONDEPAPA.VENTA
        WHERE EXISTS (
            SELECT 1
            FROM USUARIODONDEPAPA.FACTURA
            WHERE FACTURA.ID_FACTURA = VENTA.ID_FACTURA
            AND TRUNC(FACTURA.FECHA) = fecha
        );
    
    venta_record ventas_cursor%ROWTYPE;
BEGIN
    OPEN ventas_cursor;
    LOOP
        FETCH ventas_cursor INTO venta_record;
        EXIT WHEN ventas_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Venta: ' || venta_record.ID_VENTA || ', ID Plato: ' || venta_record.ID_PLATO || ', Cantidad: ' || venta_record.CANTIDAD || ', Precio: ' || venta_record.PRECIO);
    END LOOP;
    CLOSE ventas_cursor;
END;

BEGIN
    OBTENER_VENTAS_POR_FECHA(TO_DATE('2024-08-21', 'YYYY-MM-DD'));-- CAMBIAR FECHA
END;

--------------------------------------------------------
// 10.
CREATE OR REPLACE PROCEDURE OBTENER_FACTURAS_POR_ESTADO (
    estado IN NUMBER
) 
AS
    CURSOR facturas_cursor IS
        SELECT ID_FACTURA, FECHA, TOTAL
        FROM USUARIODONDEPAPA.FACTURA
        WHERE ESTADO = estado;
    
    factura_record facturas_cursor%ROWTYPE;
BEGIN
    OPEN facturas_cursor;
    LOOP
        FETCH facturas_cursor INTO factura_record;
        EXIT WHEN facturas_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Factura: ' || factura_record.ID_FACTURA || ', Fecha: ' || factura_record.FECHA || ', Total: ' || factura_record.TOTAL);
    END LOOP;
    CLOSE facturas_cursor;
END;

BEGIN
    OBTENER_FACTURAS_POR_ESTADO(1);  -- CAMBIAR ID POR ESTADO
END;

--------------------------------------------------------
// 11.
CREATE OR REPLACE PROCEDURE OBTENER_TRANSACCIONES_POR_TIPO (
    tipo_transaccion IN VARCHAR2
) 
AS
    CURSOR transacciones_cursor IS
        SELECT ID_TRANSACCION, MONTO, FECHA, DESCRIPCION
        FROM USUARIODONDEPAPA.TRANSACCIONES
        WHERE TIPO = tipo_transaccion;
    
    transaccion_record transacciones_cursor%ROWTYPE;
BEGIN
    OPEN transacciones_cursor;
    LOOP
        FETCH transacciones_cursor INTO transaccion_record;
        EXIT WHEN transacciones_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Transacción: ' || transaccion_record.ID_TRANSACCION || ', Monto: ' || transaccion_record.MONTO || ', Fecha: ' || transaccion_record.FECHA || ', Descripción: ' || transaccion_record.DESCRIPCION);
    END LOOP;
    CLOSE transacciones_cursor;
END;

BEGIN
    OBTENER_TRANSACCIONES_POR_TIPO('Pago');  -- CAMBIAR POR EL TIPO DE TRANSACCIONS
END;

--------------------------------------------------------
// 12.
CREATE OR REPLACE PROCEDURE OBTENER_USUARIOS_ACTIVOS
AS
    CURSOR usuarios_cursor IS
        SELECT ID_USUARIO, NOMBRE, CORREO
        FROM USUARIODONDEPAPA.USUARIO
        WHERE ACTIVO = 1;
    
    usuario_record usuarios_cursor%ROWTYPE;
BEGIN
    OPEN usuarios_cursor;
    LOOP
        FETCH usuarios_cursor INTO usuario_record;
        EXIT WHEN usuarios_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Usuario: ' || usuario_record.ID_USUARIO || ', Nombre: ' || usuario_record.NOMBRE || ', Correo: ' || usuario_record.CORREO);
    END LOOP;
    CLOSE usuarios_cursor;
END;

BEGIN
    OBTENER_USUARIOS_ACTIVOS;
END;

--------------------------------------------------------
// 13.
CREATE OR REPLACE PROCEDURE OBTENER_PLATOS_DISPONIBLES
AS
    CURSOR platos_cursor IS
        SELECT ID_PLATO, DESCRIPCION, PRECIO, EXISTENCIAS
        FROM USUARIODONDEPAPA.PLATO
        WHERE DISPONIBLE = 1;
    
    plato_record platos_cursor%ROWTYPE;
BEGIN
    OPEN platos_cursor;
    LOOP
        FETCH platos_cursor INTO plato_record;
        EXIT WHEN platos_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Plato: ' || plato_record.ID_PLATO || ', Descripción: ' || plato_record.DESCRIPCION || ', Precio: ' || plato_record.PRECIO || ', Existencias: ' || plato_record.EXISTENCIAS);
    END LOOP;
    CLOSE platos_cursor;
END;

BEGIN
    OBTENER_PLATOS_DISPONIBLES;
END;

--------------------------------------------------------
// 14.
CREATE OR REPLACE PROCEDURE OBTENER_FACTURAS_POR_USUARIO (
    id_usuario IN NUMBER
) 
AS
    CURSOR facturas_cursor IS
        SELECT ID_FACTURA, FECHA, TOTAL, ESTADO
        FROM USUARIODONDEPAPA.FACTURA
        WHERE ID_USUARIO = id_usuario;
    
    factura_record facturas_cursor%ROWTYPE;
BEGIN
    OPEN facturas_cursor;
    LOOP
        FETCH facturas_cursor INTO factura_record;
        EXIT WHEN facturas_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Factura: ' || factura_record.ID_FACTURA || ', Fecha: ' || factura_record.FECHA || ', Total: ' || factura_record.TOTAL || ', Estado: ' || factura_record.ESTADO);
    END LOOP;
    CLOSE facturas_cursor;
END;

BEGIN
    OBTENER_FACTURAS_POR_USUARIO(:id_usuario);
END;

--------------------------------------------------------
// 15.
CREATE OR REPLACE PROCEDURE OBTENER_RESERVAS_POR_NOMBRE (
    nombre_cliente IN VARCHAR2
) 
AS
    CURSOR reservas_cursor IS
        SELECT ID_RESERVACION, HORA, NUMERO_DE_MESA, CONTACTO
        FROM USUARIODONDEPAPA.RESERVACION
        WHERE NOMBRE = nombre_cliente;
    
    reserva_record reservas_cursor%ROWTYPE;
BEGIN
    OPEN reservas_cursor;
    LOOP
        FETCH reservas_cursor INTO reserva_record;
        EXIT WHEN reservas_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Reservación: ' || reserva_record.ID_RESERVACION || ', Hora: ' || reserva_record.HORA || ', Número de Mesa: ' || reserva_record.NUMERO_DE_MESA || ', Contacto: ' || reserva_record.CONTACTO);
    END LOOP;
    CLOSE reservas_cursor;
END;


BEGIN
    OBTENER_RESERVAS_POR_NOMBRE('Juan');
END;

