-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--PROYECTO 2- LENGUAJES DE BASES DE DATOS - JUAN PABLO VINDAS SUAREZ, SEBASTIAN SEGURA SAENZ, ROGER FERNANDO PEREIRA SANCHES, MATIAS VARGAS UMAï¿½A
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------
-- CREACION DE USUARIOS Y ASIGNACION DE ROLES.
--------------------------------------------------------
// Asignacion de permisos para crear el usuario 
alter session set "_ORACLE_SCRIPT"=true;

// Creacion del usuario
CREATE USER usuarioDondePapa IDENTIFIED BY "4567.";

// Asignacion de permisos de usuario 
GRANT CONNECT, RESOURCE TO usuarioDondePapa;
GRANT DBA TO usuarioDondePapa;

--------------------------------------------------------
-- CREACION DE TABLAS
--------------------------------------------------------
// CATEGORIA
CREATE TABLE usuarioDondePapa.categoria (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR2(255),
    disponible NUMBER(1),
    ruta_imagen VARCHAR2(1024)
);

// PLATO
CREATE TABLE usuarioDondePapa.plato (
    id_plato NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria NUMBER NOT NULL,
    descripcion VARCHAR2(255) NOT NULL,
    detalle VARCHAR2(1600) NOT NULL,
    precio NUMBER,
    existencias NUMBER NOT NULL,
    ruta_imagen VARCHAR2(1024),
    disponible NUMBER(1)
);

// RESERVACION
CREATE TABLE usuarioDondePapa.reservacion (
    id_reservacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255),
    hora DATE,
    numero_de_mesa NUMBER,
    contacto VARCHAR2(255)
);

// USUARIO
CREATE TABLE usuarioDondePapa.usuario (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(20) NOT NULL,
    password VARCHAR2(512) NOT NULL,
    nombre VARCHAR2(20) NOT NULL,
    apellidos VARCHAR2(30) NOT NULL,
    correo VARCHAR2(1024),
    telefono VARCHAR2(15),
    ruta_imagen VARCHAR2(1024),
    activo NUMBER(1)
);

// FACTURA
CREATE TABLE usuarioDondePapa.factura (
    id_factura NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    fecha DATE,
    total NUMBER,
    estado NUMBER
);

// VENTA
CREATE TABLE usuarioDondePapa.venta (
    id_venta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_factura NUMBER NOT NULL,
    id_plato NUMBER NOT NULL,
    precio NUMBER,
    cantidad NUMBER
);

// ROL
CREATE TABLE usuarioDondePapa.rol (
    id_rol NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(20),
    id_usuario NUMBER
);

// TRANSACCION
CREATE TABLE usuarioDondePapa.transacciones (
    id_transaccion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    tipo VARCHAR2(50),
    monto NUMBER(10, 2),
    fecha DATE,
    descripcion VARCHAR2(255)
);

--------------------------------------------------------
-- FOREIGN KEYS
--------------------------------------------------------

// PLATO
ALTER TABLE usuarioDondePapa.plato
ADD CONSTRAINT fk_producto_categoria FOREIGN KEY (id_categoria) REFERENCES usuarioDondePapa.categoria(id_categoria);

// FACTURA
ALTER TABLE usuarioDondePapa.factura
ADD CONSTRAINT fk_factura_usuario FOREIGN KEY (id_usuario) REFERENCES usuarioDondePapa.usuario(id_usuario);

// VENTA
ALTER TABLE usuarioDondePapa.venta
ADD CONSTRAINT fk_ventas_factura FOREIGN KEY (id_factura) REFERENCES usuarioDondePapa.factura(id_factura);
ALTER TABLE usuarioDondePapa.venta
ADD CONSTRAINT fk_ventas_plato FOREIGN KEY (id_plato) REFERENCES usuarioDondePapa.plato(id_plato);

// ROL
ALTER TABLE usuarioDondePapa.rol
ADD CONSTRAINT fk_rol_usuario FOREIGN KEY (id_usuario) REFERENCES usuarioDondePapa.usuario(id_usuario);

// TRANSACCIONES
ALTER TABLE usuarioDondePapa.transacciones
ADD CONSTRAINT fk_transacciones_usuario FOREIGN KEY (id_usuario) REFERENCES usuarioDondePapa.usuario(id_usuario);

--------------------------------------------------------
-- INSERTS
--------------------------------------------------------
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES 
    ('Sï¿½ndwiches', 1, 'https://i.blogs.es/1cbc97/collage_sanwich/1366_2000.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES 
    ('Sopas', 1, 'https://i.blogs.es/4f9a7f/collage-seis-fotos-portada-dap/650_1200.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES 
    ('Wraps', 1, 'https://www.gourmet.cl/wp-content/uploads/2016/09/wrap-de-pollo.jpg-editada.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES 
    ('Quesadillas', 1, 'https://www.lechedeflorida.com/core/fileparse.php/267/urlt/BBQ-PORK-QUESADILLA-web.png');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES 
    ('Ticos', 1, 'https://i.ytimg.com/vi/VCIc5JO_6pQ/maxresdefault.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES 
    ('Arroz', 1, 'https://www.ecestaticos.com/image/clipping/1440/1080/c45466fb9f76baa6eebf80a4194592d7/los-trucos-para-que-te-quede-el-arroz-perfecto.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES 
    ('Mariscos', 1, 'https://www.eluniversal.com.mx/resizer/04M0CFm2P8H_U3CdE4co_RWqRkQ=/1100x666/cloudfront-us-east-1.images.arcpublishing.com/eluniversal/PEKLULINHNCMHM3DVNV6ORRI5M.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES 
    ('Pastas', 1, 'https://casadiromavlc.com/wp-content/uploads/2019/08/tipos-de-pastas-y-salsas-cover-1080x675.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES 
    ('Pollos', 1, 'https://s1.eestatic.com/2015/06/10/cocinillas/cocinillas_40006005_116187701_1706x960.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES 
    ('Hamburguesas', 1, 'https://cdn2.cocinadelirante.com/sites/default/files/images/2023/08/recetas-de-hamburguesas-caseras.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES 
    ('Carnes', 1, 'https://img.freepik.com/foto-gratis/carne-cruda-mesa_23-2150857912.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES 
    ('Guarniciones', 1, 'https://static.bonviveur.es/tags/las-mejores-recetas-de-guarniciones.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES 
    ('Especial', 1, 'https://previews.123rf.com/images/acceptphoto/acceptphoto1703/acceptphoto170300049/73290879-variedad-de-platos-especiales-en-peque%C3%B1as-placas-blancas.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES 
    ('Para Picar', 1, 'https://hips.hearstapps.com/hmg-prod/images/huevos-rellenos-de-hummus-1552479730.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES 
    ('Bocas del mar', 1, 'https://www.bocasdelmar.com/wp-content/uploads/2019/01/eatandrink2.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES 
    ('tacos gallos', 1, 'https://www.cocinatis.com/archivos/202207/tacos-mexicanos-con-pico-gallo_large_16x9.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES 
    ('Bocas y tierra tica', 1, 'https://media-cdn.tripadvisor.com/media/photo-s/1b/4e/54/49/plato-de-bocas-surtido.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES 
    ('Bocas clasicas', 1, 'https://enbocacr.com/wp-content/uploads/2023/06/platos-enboca-2023-1.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES 
    ('Bebidas Donde Papï¿½', 1, 'https://aprende.com/wp-content/uploads/2022/10/bebidas-naturales.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES 
    ('Licores', 1, 'https://thefoodtech.com/wp-content/uploads/2020/05/productos-diaego.jpg');
INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen) VALUES 
    ('Postres', 1, 'https://i.blogs.es/1c733d/postres/1366_2000.jpg');

INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Ensalada Cï¿½sar', 'Con quesito parmesano y cuadritos de pan tostado con nuestro pollo grill.', 4500, 10, 1, 1, 'https://www.gourmet.cl/wp-content/uploads/2016/09/Ensalada_C%C3%A9sar-web-553x458.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Ensalada Caprese', 'Ensalada italiana de san pelegrino resaltada por rodajas de tomate y el sabor de la albahaca fresca.', 4500, 10, 1, 1, 'https://i.blogs.es/5ca73e/ensalada-caprese-rehacer-pakus-dap/1366_2000.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Ensalada Pescado', 'Ensalada con cuadritos de pan tostado con nuestro empanizado, al ajillo o grill', 4500, 10, 1, 1, 'https://www.recetasnestle.com.do/sites/default/files/srh_recipes/47b45c7192d1d88acff53e7064202d4f.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Sï¿½ndwich de Pollo', 'Con pan ciabatta, nuestro sï¿½ndwich de pollo, lechuga, tomate y deliciosas salsa clï¿½sicas', 3700, 10, 2, 1, 'https://images.aws.nestle.recipes/original/0dcdbe631b092077fd7e411236c4b06d_sandwich_de_pollo_a_las_finas_hierbas_-_mx_ponte_bien.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Sï¿½ndwich de Jamï¿½n y Queso', 'Deliciosa crepa de pollo en su salsa blanca', 3200, 10, 2, 1, 'https://www.comedera.com/wp-content/uploads/2021/03/sandwich-de-jamon-y-queso.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Sï¿½ndwich de Carne', 'Con pan ciabatta, nuestro sï¿½ndwich de jamï¿½n y queso, lechuga, tomate y deliciosas salsa clï¿½sicas.', 4000, 10, 2, 1, 'https://www.gourmet.cl/wp-content/uploads/2016/05/Sandwich-de-Carne-Mechada-con-cebolla-caramelizada-y-tomates-asados.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Sopa Azteca', 'La sopa de tomate por excelencia traï¿½da directo de Mï¿½xico por papï¿½.', 4000, 10, 3, 1, 'https://cdn0.recetasgratis.net/es/posts/6/0/5/sopa_azteca_35506_600_square.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Sopa de Mariscos', 'Compuesta por mariscos frescos, y el toque esencial de papï¿½.', 4500, 10, 3, 1, 'https://www.comedera.com/wp-content/uploads/2018/03/sopa-de-marisco.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Sopa de Pollo', 'Para sacarnos de cualquier apuro, la sopa curativa clï¿½sica.', 3300, 10, 3, 1, 'https://especiasmontero.com/wp-content/uploads/2018/02/CaldoDePollo-1.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Sopa de Rabo', 'Sacando lo mejor de los ingredientes traemos la sopa preferida de papï¿½.', 4000, 10, 3, 1, 'https://rumbameats.com/wp-content/uploads/2019/07/Hervido-de-_rabo-by-enrilemoine-7.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Sopa de Mondongo', 'Sopa tradicional de la tierra costarricense para un antojo de antaï¿½o.', 3500, 10, 3, 1, 'https://recetasdemicolombia.com/wp-content/uploads/2020/08/mondongo-500x375.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Wrap de Pollo y Bacon', 'Wrap relleno de pollo empanizado, delicioso tocino y nuestra salsa mayonesa chipotle.', 3500, 10, 4, 1, 'https://i.pinimg.com/736x/72/86/1b/72861baeaccca244bf2fee091a7dc675.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Wrap corvina', 'Wrap con pescado empanizado y nuestra clï¿½sica salsa tï¿½rtara.', 3500, 10, 4, 1, 'https://i.pinimg.com/736x/f5/f7/9a/f5f79aa520c59e342d7c08a8fe3e9174.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Quesadillia Crï¿½pe', 'Deliciosa crepa de pollo en su sala blanca.', 3500, 10, 5, 1, 'https://thasneen.com/cooking/wp-content/uploads/2017/06/Indian-style-Quesadilla.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Quesadillias de Pollo o Carne ', 'Con dos quesos, mozzarella y cheddar, disfrï¿½talas como quieras!', 3700, 10, 5, 1, 'https://i.ytimg.com/vi/7J5JqSOP-1s/maxresdefault.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Quesadillias mixtas ', 'Mezcla de los dos mundos, pollo y carne en uno solo.', 4000, 10, 5, 1, 'https://assets.unileversolutions.com/recipes-v2/231998.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Casados', 'Clï¿½sico plato que todos los ticos reconocemos, salvador de tandas, escoge entre mechada, pescado, pollo, chuleta o bistec.', 3500, 10, 6, 1, 'https://upload.wikimedia.org/wikipedia/commons/0/08/Casado_costarricense.png');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Chifrijo', 'Para los amantes de la combinaciï¿½n del chicharrï¿½n, frijoles y arroz, servido con el clï¿½sico oro verde y tortillitas para que amarre.', 3500, 10, 6, 1, 'https://okdiario.com/img/2020/05/07/receta-de-costa-rica_-chifrijo-1.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Chicharrones', 'El sabor de Puriscal hasta tu mesa, servido con yuca frita y ensalada a lo tico.', 3800, 10, 6, 1, 'https://www.cocinatis.com/archivos/202308/ctis1012-receta-chicharrones-de-cerdo-andaluces-1280x720x80xX.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Lengua en Salsa', 'Atrï¿½vete a probar nuestra suave lengua en salsa de tomate, calla hasta los mï¿½s bocï¿½nes con su sabor.', 4800, 10, 6, 1, 'https://www.recetascostarica.com/base/stock/Recipe/272-image/272-image_web.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Patitas de Cerdo', 'Patitas de cerdo con frijolitos blancos, plato lleno de puro sabor donde mi tata.', 4000, 10, 6, 1, 'https://www.nutricienta.com/imagenes/alimentos/alimento-nutricienta-manitas-de-cerdo.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Patacones', 'Perfecto para quitarse esas ganas de comer a lo tico, nuestros patacones vienen con carne mechada, frijoles molidos y pico de gallo.', 3700, 10, 6, 1, 'https://www.semana.com/resizer/D-Lcez1Rj4bSIUHKyMk9rwDRIMY=/1280x720/smart/filters:format(jpg):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/semana/CUVSFJ3V5ZEWVLBJ76BASDV2PY.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Rice and Beans', 'Limï¿½n presente en el menï¿½ de papï¿½, pollo en salsa caribeï¿½a con ensalada y maduros con el inigualable rice and beans.', 4500, 10, 6, 1, 'https://www.allrecipes.com/thmb/YywjEMDfUzEtxUR_8i_B_4dd-7o=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/211325-b6b1befbb1644f9b93e66eee74dbe07f.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Chilli Relleno', 'Relleno de carne molida, un excelente plato para el buen tico.', 4200, 10, 6, 1, 'https://www.jennieo.com/wp-content/uploads/2019/11/image-recipe_turkey-and-spinach-chile-relleno-with-fresh-tomato-sauce.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Arroz con Carne', 'Arroz directo de la casa compuesto por una combinaciï¿½n perfecta de arroz y carne.', 4000, 10, 7, 1, 'https://recetacubana.com/wp-content/uploads/2019/12/receta-Arroz-con-Carne-de-Cerdo.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Arroz con Pollo', 'Arroz con el pollo desmechado clï¿½sico, haciendo de este un plato tï¿½pico delicioso.', 3700, 10, 7, 1, 'https://img.bekiacocina.com/cocina/0000/179-h.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Arroz con Marinera', 'Elaborado con los mariscos mï¿½s frescos seleccionados por papï¿½.', 4500, 10, 7, 1, 'https://www.elespectador.com/resizer/iSDLgK_Xt86uhsXCmvAN_Jp0Elk=/1200x675/filters:quality(60):format(jpeg)/cloudfront-us-east-1.images.arcpublishing.com/elespectador/QT2HQD77JJGDTIYXU4COEHGIRE.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Arroz con Camarones', 'Arroz con camarones de alta calidad para saciar los paladares hambrientos.', 4500, 10, 7, 1, 'https://www.recetasnestle.com.ec/sites/default/files/srh_recipes/b5761ed0a862a8c3ae9980304cd22ded.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Pomodoro', 'Nuestra pasta en salsa de tomate con delicioso queso mozzarella.', 3500, 10, 9, 1, 'https://supermancooks.com/wp-content/uploads/2023/03/pasta-pomodoro-featured.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Bolognese', 'Deliciosa pasta con queso mozzarella, salsa de tomate y carne molida.', 3800, 10, 9, 1, 'https://feelgoodfoodie.net/wp-content/uploads/2023/04/Pasta-Bolognese-TIMG.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Marinera', 'Salsa de tomate o salsa blanca con mariscos o solo camarones.', 4500, 10, 9, 1, 'https://newmansown.com/wp-content/uploads/2022/03/shrimp-marinara-with-pasta.png');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Alfredo', 'Pasta con jamï¿½n y hongos en salsa blanca.', 4000, 10, 9, 1, 'https://images.aws.nestle.recipes/resized/cc72869fabfc2bdfa036fd1fe0e2bad8_creamy_alfredo_pasta_long_left_1080_850.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Filet de Corvina', 'Filet de corvina al grill, al ajillo o empanizado.', 4800, 10, 8, 1, 'https://pronacatqma.com/images/com_yoorecipe/banner_superior/8264_1.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Corvina Entera', 'Nuestra especial corvina entera sin espinas lista para ti.', 6700, 10, 8, 1, 'https://canalcocina.es/medias/images/1101_CocContigo_CorvinaHorno.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Pargo Entero', 'Pargo entero fresco para los que quieran recordar los dï¿½as de playa.', 5800, 10, 8, 1, 'https://d1uz88p17r663j.cloudfront.net/original/cd153cfbb9d153b1786c7d45adac52b2_Pargo-rojo-al-sarten.png');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Corvina Entera a la Caribeï¿½a', 'Nuestra especial corvina entera acompaï¿½ada de salsa caribeï¿½a y camarones.', 8700, 10, 8, 1, 'https://media-cdn.tripadvisor.com/media/photo-s/18/2f/ec/5f/corvina-entera-frita.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Camarones', 'Jugosos camarones empanizados o al ajillo para los fanï¿½ticos del mar.', 4700, 10, 8, 1, 'https://cloudfront-us-east-1.images.arcpublishing.com/elespectador/WFY4CMXRGZD3TA2FXSRPU7UDOA.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Mariscada', 'Mix de mariscos frescos cocinados al ajillo creando un platillo colorido.', 4500, 10, 8, 1, 'https://imag.bonviveur.com/mariscada-gallega.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Mejillones', 'Mejillones noruegos al ajillo seleccionados por papï¿½.', 4800, 10, 8, 1, 'https://coyomar.es/wp-content/uploads/2022/06/Como-cocer-mejillones-1024x768.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Pollo al Grill', 'Nuestro especial pollo, tratado por la mano de nuestros chefs, a la parrilla.', 4000, 10, 10, 1, 'https://storage.googleapis.com/fitia-api-bucket/media/images/recipe_images/1006680.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Pollo a la Jalapeï¿½a', 'Pollo parrillero con ganas de mï¿½s fuego, baï¿½ado en nuestra salsa especial de jalapeï¿½os.', 4500, 10, 10, 1, 'https://i.ytimg.com/vi/ChLkloORDfU/maxresdefault.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Pollo Cordon Bleu', 'Nuestro pollo en un platillo fabuloso, cordon bleu baï¿½ado en salsa blanca.', 4000, 10, 10, 1, 'https://i.ytimg.com/vi/i2fwv6beoT8/maxresdefault.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Hamburguesa Donde Papï¿½', 'Exquisita hamburguesa de papï¿½, pulled pork BBQ, pepinillos, bacon, aros de cebolla.', 4800, 10, 11, 1, 'https://delination.com/wp-content/uploads/2022/11/Hamburguesa-casera-de-res-con-papas-850x550.jpeg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Hamburguesa de Pollo', 'Una de las mejores hamburguesas para los fans del pollo a la parrilla.', 4500, 10, 11, 1, 'https://www.comedera.com/wp-content/uploads/2023/07/Hamburguesa-de-pollo-picante.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Hamburguesa con Queso', 'Hamburguesa con queso de papï¿½, para saborear a gusto.', 3500, 10, 11, 1, 'https://pronacatqma.com/images/com_yoorecipe/banner_superior/18096_1.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Hamburguesa de Pescado', 'Hamburguesa de pescado con salsa tï¿½rtara, lechuga y queso amarillo, solo... donde papï¿½.', 4200, 10, 11, 1, 'https://editorialtelevisa.brightspotcdn.com/wp-content/uploads/2020/03/recetas-con-filete-de-pescado-fa%25CC%2581ciles-hamburguesa.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Costillas', 'Costilla de cerdo cocinada especialmente 3 horas por nuestros chefs.', 4800, 10, 14, 1, 'https://t1.uc.ltmcdn.com/es/posts/3/9/5/como_hacer_costillas_bbq_en_sarten_50593_orig.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Churrasco ', 'Este delicioso corte proviene de la falda de la res, cortado transversalmente, tratado por papï¿½.', 5800, 10, 12, 1, 'https://cdn0.recetasgratis.net/es/posts/2/3/1/churrasco_a_lo_pobre_77132_orig.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Churrasco a la Jalapeï¿½a ', 'Churrasco en nuestra salsa especial a la jalapeï¿½a para darle su perfecto toque picante.', 6500, 10, 12, 1, 'https://media-cdn.tripadvisor.com/media/photo-m/1280/29/75/59/9e/churrasco-tipico.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Lomito ', 'Destacado por su suavidad natural, este corte de caracterï¿½sticas jugosas puede saciar a cualquiera.', 6200, 10, 12, 1, 'https://www.clarin.com/2021/07/26/u-aUfp64d_1200x0__1.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Lomito a la jalapeï¿½a', 'Para aquellos que quieran probar la parrilla de papï¿½, el suave lomito en combinaciï¿½n con nuestro toque a la jalapeï¿½a.', 6800, 10, 12, 1, 'https://media-cdn.tripadvisor.com/media/photo-s/11/0c/bc/c4/puntas-de-lomito-a-la.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Purï¿½', 'Suave y cremoso purï¿½ de papas, hecho con papas seleccionadas y un toque de mantequilla, ideal para complementar cualquier plato principal. Servido caliente', 1000, 10, 13, 1, 'https://images.aws.nestle.recipes/original/892d65cba81876ed7c340ae9ce7663d3_DCS_MARZO_INSTAGRAM-04.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Vegetales', 'Mix de vegetales de temporada, cocidos al vapor para preservar su frescura y sabor natural. Una opciï¿½n saludable y colorida.', 1000, 10, 13, 1, 'https://cdn.aarp.net/content/aarpe/es/home/salud/vida-saludable/info-2023/comer-vegetales-verduras-crudos-o-cocidos/_jcr_content/root/container_main/container_body_main/container_body1/container_body_cf/container_image/articlecontentfragment/cfimage.coreimg.50.932.jpeg/content/dam/aarp/health/healthy-living/2023/07/1140-colorfulrawveggies-esp.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Papas asadas', 'Papas asadas hasta lograr una piel crujiente y un interior suave, sazonadas con hierbas finas y un toque de aceite de oliva.', 1000, 10, 13, 1, 'https://www.gourmet.cl/wp-content/uploads/2014/09/Papas-Asadas.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Arroz', 'Arroz blanco esponjoso, cocido a la perfecciï¿½n, un bï¿½sico indispensable para acompaï¿½ar una variedad de platos.', 1000, 10, 13, 1, 'https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/05bab5cb-f8b6-487d-a509-f38031ea2708/Derivates/142b07d0-cedc-44f8-8569-e0222afab308.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Papas fritas', 'Papas fritas doradas y crujientes, cortadas a mano y fritas en aceite de alta calidad, con un toque de sal marina para realzar su sabor.', 1000, 10, 13, 1, 'https://phantom-marca.unidadeditorial.es/813d16708dc72860fd3cf319c9a245b5/resize/828/f/jpg/assets/multimedia/imagenes/2023/08/04/16911461030527.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Yuca Frita', 'Yuqitas a lo tico, fritas apenas para un gusto.', 1800, 10, 15, 1, 'https://mexicanappetizersandmore.com/wp-content/uploads/Yuca-Frita-1-12.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Patacones', 'Patacones clï¿½sicos con frijoles molidos y pico de gallo.', 1800, 10, 15, 1, 'https://images.hola.com/imagenes/cocina/recetas/20200320163599/receta-patacones-platano/0-800-862/patacones-adobe-m.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Aros de Cebolla', 'Aros de cebolla crujientes por fuera y por dentro!', 2200, 10, 15, 1, 'https://images.hola.com/imagenes/cocina/recetas/20220209204312/aros-cebolla-crujientes/1-49-243/aros-cebolla-adobe-t.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Papas Gajo', 'El estilo de papas favoritas de papï¿½, pide las que quieres.', 2200, 10, 15, 1, 'https://www.paulinacocina.net/wp-content/uploads/2023/11/receta-de-papas-gajo-Paulina-Cocina-Recetas.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Papas Francesas', 'Papas fritas apenas para acompaï¿½ar tu comida.', 1800, 10, 15, 1, 'https://www.paulinacocina.net/wp-content/uploads/2015/08/P1140112-e1439267676931.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Palitos de Queso', 'Palitos de queso mozzarella, de la mejor compaï¿½ï¿½a que puedas tener.', 2200, 10, 15, 1, 'https://mandolina.co/wp-content/uploads/2023/06/deditos-de-queso-1200x900.png');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Gallos de salchichï¿½n', 'Deliciosos gallos de salchichï¿½n.', 2000, 10, 17, 1, 'https://tortiricascentroamerica.com/wp-content/uploads/2016/01/receta-tortiricas-gallitos-faciles.png');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Gallos de Chorizo', 'Deliciosos gallos de chorizo.', 2000, 10, 17, 1, 'https://cloudfront-us-east-1.images.arcpublishing.com/gruponacion/QZ7BD6VNOVFFPDH7VAWWQTRFTY.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Tacos ', 'Deliciosos tacos.', 2000, 10, 17, 1, 'https://www.comedera.com/wp-content/uploads/2017/08/tacos-al-pastor-receta.jpg');
INSERT INTO usuarioDondePapa.plato (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Tacos de Camaron', 'Deliciosos tacos de camaron.', 2700, 10, 17, 1, 'https://t2.uc.ltmcdn.com/es/posts/2/8/1/como_hacer_tacos_de_camaron_enchilado_51182_orig.jpg');

INSERT INTO usuarioDondePapa.reservacion (nombre, hora, numero_de_mesa, contacto) VALUES 
    ('Juan', TO_DATE('14:30:00', 'HH24:MI:SS'), 1, '88269654');
INSERT INTO usuarioDondePapa.reservacion (nombre, hora, numero_de_mesa, contacto) VALUES 
    ('Marï¿½a', TO_DATE('13:00:00', 'HH24:MI:SS'), 2, '88269655');
INSERT INTO usuarioDondePapa.reservacion (nombre, hora, numero_de_mesa, contacto) VALUES 
    ('Josï¿½', TO_DATE('20:00:00', 'HH24:MI:SS'), 3, '88269656');

INSERT INTO usuarioDondePapa.usuario (username, password, nombre, apellidos, correo, telefono, ruta_imagen, activo) VALUES 
    ('juan', '$2a$12$RnK02njwwqKfsnWd1C8bAOfOsXQIZZbYkCbCkobm1ohrIYLqp2wTS', 'Juan', 'Castro Mora', 'jcastro@gmail.com', '4556-8978', 'https://img.freepik.com/foto-gratis/chico-guapo-seguro-posando-contra-pared-blanca_176420-32936.jpg', 1);
INSERT INTO usuarioDondePapa.usuario (username, password, nombre, apellidos, correo, telefono, ruta_imagen, activo) VALUES 
    ('lafit', '$2a$12$AltEHO7MblmOstrGBZCw7e0qbuQao14T64RzXMs8wYE2ZYouua3IK', 'Chuty', 'Villalobos', 'chutyvillalobos@gmail.com', '5456-8789', 'https://pbs.twimg.com/media/EahiQBxX0AEud1m.jpg', 1);
INSERT INTO usuarioDondePapa.usuario (username, password, nombre, apellidos, correo, telefono, ruta_imagen, activo) VALUES 
    ('allan', '$2a$12$FiuxTsChejWyYJp/gv9YauSFeE3AdT3QsMiag3SQFsQHQnqEFNqR.', 'Allan', 'Allan Loria', 'allanlafit@gmail.com', '7898-8936', 'https://www.diarioextra.com/files/Dnews/images/detail/500526_allanvillalobos.jpg', 1);

INSERT INTO usuarioDondePapa.rol (nombre, id_usuario) VALUES 
    ('ROLE_ADMIN', 1);
INSERT INTO usuarioDondePapa.rol (nombre, id_usuario) VALUES 
    ('ROLE_VENDEDOR', 2);
INSERT INTO usuarioDondePapa.rol (nombre, id_usuario) VALUES 
    ('ROLE_USER', 3);

INSERT INTO usuarioDondePapa.factura (id_usuario, fecha, total, estado) VALUES 
    (1, TO_DATE('2024-01-05', 'YYYY-MM-DD'), 211560, 2);
INSERT INTO usuarioDondePapa.factura (id_usuario, fecha, total, estado) VALUES 
    (2, TO_DATE('2024-01-07', 'YYYY-MM-DD'), 554340, 2);
INSERT INTO usuarioDondePapa.factura (id_usuario, fecha, total, estado) VALUES 
    (3, TO_DATE('2024-01-07', 'YYYY-MM-DD'), 871000, 2);
INSERT INTO usuarioDondePapa.factura (id_usuario, fecha, total, estado) VALUES 
    (1, TO_DATE('2024-01-15', 'YYYY-MM-DD'), 244140, 1);
INSERT INTO usuarioDondePapa.factura (id_usuario, fecha, total, estado) VALUES 
    (2, TO_DATE('2024-01-17', 'YYYY-MM-DD'), 414800, 1);
INSERT INTO usuarioDondePapa.factura (id_usuario, fecha, total, estado) VALUES 
    (3, TO_DATE('2024-01-21', 'YYYY-MM-DD'), 420000, 1);

INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES 
    (1, 5, 45000, 3);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES 
    (2, 9, 15780, 2);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES 
    (3, 10, 15000, 3);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES 
    (1, 2, 45000, 1);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES 
    (2, 14, 154000, 3);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES 
    (2, 9, 15780, 3);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES 
    (3, 14, 154000, 1);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES 
    (3, 6, 57000, 1);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES 
    (3, 15, 330000, 2);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES 
    (1, 6, 57000, 2);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES 
    (1, 8, 27600, 3);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES 
    (1, 9, 15780, 3);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES 
    (2, 8, 27600, 3);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES 
    (2, 14, 154000, 2);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES 
    (2, 3, 24000, 1);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES 
    (3, 15, 330000, 1);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES 
    (3, 12, 45000, 1);
INSERT INTO usuarioDondePapa.venta (id_factura, id_plato, precio, cantidad) VALUES 
    (3, 10, 15000, 3);
COMMIT;

--------------------------------------------------------
-- PROCEDIMIENTOS ALMACENADOS
--------------------------------------------------------
SET SERVEROUTPUT ON;

// 1. Procedimiento para obtener los platos disponibles
CREATE OR REPLACE PROCEDURE OBTENER_PLATOS_DISPONIBLES 
AS
BEGIN
    FOR platos_disponibles IN (SELECT descripcion FROM usuarioDondePapa.plato WHERE disponible = 1) LOOP
        DBMS_OUTPUT.PUT_LINE('Plato: ' || platos_disponibles.descripcion);
    END LOOP; 
END;

EXEC OBTENER_PLATOS_DISPONIBLES;

--------------------------------------------------------

// 2. Procedimiento para calcular el total de una factura
CREATE OR REPLACE PROCEDURE CALCULAR_TOTAL_FACTURA (
    id_factura IN NUMBER,
    total OUT NUMBER
) 
AS
BEGIN
    SELECT SUM(precio * cantidad) INTO total
    FROM usuarioDondePapa.venta
    WHERE id_factura = id_factura;
END;

DECLARE
    total NUMBER;
BEGIN
    CALCULAR_TOTAL_FACTURA(1, total);
    DBMS_OUTPUT.PUT_LINE('Total de la factura: ' || total);
END;

--------------------------------------------------------

-- 3. Procedimiento para obtener facturas por usuario
CREATE OR REPLACE PROCEDURE OBTENER_FACTURAS_POR_USUARIO (
    id_usuario IN NUMBER
) 
AS
BEGIN
    FOR facturas IN (SELECT * FROM usuarioDondePapa.factura WHERE id_usuario = id_usuario) LOOP
        DBMS_OUTPUT.PUT_LINE('ID Factura: ' || facturas.id_factura || ', Fecha: ' || facturas.fecha || ', Total: ' || facturas.total || ', Estado: ' || facturas.estado);
    END LOOP;
END;

EXEC OBTENER_FACTURAS_POR_USUARIO(1);

--------------------------------------------------------

-- 4. Procedimiento para insertar nueva categoria
CREATE OR REPLACE PROCEDURE INSERTAR_CATEGORIA (
    descripcion IN VARCHAR2,
    disponible IN NUMBER,
    ruta_imagen IN VARCHAR2
) 
AS
BEGIN
    INSERT INTO usuarioDondePapa.categoria (descripcion, disponible, ruta_imagen)
    VALUES (descripcion, disponible, ruta_imagen);
END;


BEGIN
    INSERTAR_CATEGORIA('Bebidas', 1, 'ruta/a/imagen');
END;

--------------------------------------------------------

// 5. Procedimiento para obtener ventas por plato
CREATE OR REPLACE PROCEDURE OBTENER_VENTAS_POR_PLATO (
    id_plato IN NUMBER
) 
AS
BEGIN
    FOR ventas IN (SELECT * FROM usuarioDondePapa.venta WHERE id_plato = id_plato) LOOP
        DBMS_OUTPUT.PUT_LINE('ID Venta: ' || ventas.id_venta || ', ID Factura: ' || ventas.id_factura || ', Precio: ' || ventas.precio || ', Cantidad: ' || ventas.cantidad);
    END LOOP;
END;

EXEC OBTENER_VENTAS_POR_PLATO(1);

--------------------------------------------------------

// 6. Procedimiento para insertar un nuevo plato
CREATE OR REPLACE PROCEDURE INSERTAR_PLATO (
    id_categoria IN NUMBER,
    descripcion IN VARCHAR2,
    detalle IN VARCHAR2,
    precio IN NUMBER,
    existencias IN NUMBER,
    ruta_imagen IN VARCHAR2,
    disponible IN NUMBER
) 
AS
BEGIN
    INSERT INTO usuarioDondePapa.plato (id_categoria, descripcion, detalle, precio, existencias, ruta_imagen, disponible)
    VALUES (id_categoria, descripcion, detalle, precio, existencias, ruta_imagen, disponible);
END;

BEGIN
    INSERTAR_PLATO(1, 'Plato Ejemplo', 'Detalle del Plato', 100, 10, 'ruta/a/imagen', 1);
END;

--------------------------------------------------------

// 7. Procedimiento para actualizar categoria
CREATE OR REPLACE PROCEDURE ACTUALIZAR_CATEGORIA (
    id_categoria IN NUMBER,
    descripcion IN VARCHAR2,
    disponible IN NUMBER,
    ruta_imagen IN VARCHAR2
) 
AS
BEGIN
    UPDATE usuarioDondePapa.categoria
    SET descripcion = descripcion,
        disponible = disponible,
        ruta_imagen = ruta_imagen
    WHERE id_categoria = id_categoria;
END;


BEGIN
    ACTUALIZAR_CATEGORIA(1, 'Bebidas Actualizadas', 1, 'ruta/a/nueva/imagen');
END;

--------------------------------------------------------

// 8. Procedimiento para eliminar una reservacion
CREATE OR REPLACE PROCEDURE ELIMINAR_RESERVACION (
    p_id_reservacion IN NUMBER
) 
AS
BEGIN
    DELETE FROM usuarioDondePapa.reservacion
    WHERE id_reservacion = p_id_reservacion;
END;
/

BEGIN
    ELIMINAR_RESERVACION(1);
END;

--------------------------------------------------------

// 9. Procedimiento para insertar nuevo plato
CREATE OR REPLACE PROCEDURE INSERTAR_NUEVO_PLATO (
    id_categoria IN NUMBER,
    descripcion IN VARCHAR2,
    detalle IN VARCHAR2,
    precio IN NUMBER,
    existencias IN NUMBER,
    ruta_imagen IN VARCHAR2,
    disponible IN NUMBER
) 
AS
BEGIN
    INSERT INTO usuarioDondePapa.plato (id_categoria, descripcion, detalle, precio, existencias, ruta_imagen, disponible)
    VALUES (id_categoria, descripcion, detalle, precio, existencias, ruta_imagen, disponible);
END;

BEGIN
    INSERTAR_NUEVO_PLATO(1, 'Otro Plato Ejemplo', 'Otro Detalle del Plato', 120, 20, 'ruta/a/otra/imagen', 1);
END;

--------------------------------------------------------

// 10. Procedimiento para eliminar un plato 
CREATE OR REPLACE PROCEDURE ELIMINAR_PLATO (
    p_id_plato IN NUMBER
) 
AS
BEGIN
    -- Primero, eliminar las referencias en la tabla ventas
    DELETE FROM usuarioDondePapa.venta
    WHERE id_plato = p_id_plato;

    -- Luego, eliminar el plato en la tabla plato
    DELETE FROM usuarioDondePapa.plato
    WHERE id_plato = p_id_plato;
END;
/

BEGIN
    ELIMINAR_PLATO(55);
END;

--------------------------------------------------------

// 11. Procedimiento para obtener el total de ventas por usuario
CREATE OR REPLACE PROCEDURE OBTENER_TOTAL_VENTAS_POR_USUARIO (
    id_usuario IN NUMBER
) 
AS
BEGIN
    FOR ventas IN (SELECT f.id_usuario, SUM(v.precio * v.cantidad) AS total_ventas
                   FROM usuarioDondePapa.venta v
                   JOIN usuarioDondePapa.factura f ON v.id_factura = f.id_factura
                   WHERE f.id_usuario = id_usuario
                   GROUP BY f.id_usuario) LOOP
        DBMS_OUTPUT.PUT_LINE('ID Usuario: ' || ventas.id_usuario || ', Total Ventas: ' || ventas.total_ventas);
    END LOOP;
END;

EXEC OBTENER_TOTAL_VENTAS_POR_USUARIO(1);

--------------------------------------------------------

// 12. Procedimiento para modificar la disponibilidad de un plato
CREATE OR REPLACE PROCEDURE MODIFICAR_DISPONIBILIDAD_PLATO (
    id_plato IN NUMBER,
    disponible IN NUMBER
) 
AS
BEGIN
    UPDATE usuarioDondePapa.plato
    SET disponible = disponible
    WHERE id_plato = id_plato;
END;

BEGIN
    MODIFICAR_DISPONIBILIDAD_PLATO(1, 0);
END;


--------------------------------------------------------

// 13. Filtrar por precion superior y inferior.
CREATE OR REPLACE PROCEDURE FILTRAR_PLATOS_POR_PRECIO (
    p_precio_inf IN NUMBER,
    p_precio_sup IN NUMBER
) 
AS
BEGIN
    FOR r_plato IN (SELECT descripcion, precio 
                    FROM usuarioDondePapa.plato 
                    WHERE precio BETWEEN p_precio_inf AND p_precio_sup 
                    ORDER BY descripcion ASC) 
    LOOP
        DBMS_OUTPUT.PUT_LINE('Plato: ' || r_plato.descripcion || ', Precio: ' || r_plato.precio);
    END LOOP;
END;
/

BEGIN
    -- Prueba del procedimiento con un rango de precios
    FILTRAR_PLATOS_POR_PRECIO(1000, 5000);
END;
/
--------------------------------------------------------
--14. Procedimiento para actualizar el precio de un plato.

CREATE OR REPLACE PROCEDURE ACTUALIZAR_PRECIO_PLATO (
    p_id_plato IN NUMBER,
    p_nuevo_precio IN NUMBER
) 
AS
BEGIN
    UPDATE usuarioDondePapa.plato
    SET precio = p_nuevo_precio
    WHERE id_plato = p_id_plato;
END;

BEGIN
    -- Ejecuta el procedimiento para actualizar el precio de un plato específico
    ACTUALIZAR_PRECIO_PLATO(
        1,          -- ID del plato 
        1500      -- Nuevo precio que asignar al plato
    );
END;
/

SELECT * FROM usuarioDondePapa.plato WHERE id_plato = 1;

--------------------------------------------------------
--15. Procedimiento para obtener la lista de categorías disponibles
CREATE OR REPLACE PROCEDURE OBTENER_CATEGORIAS_DISPONIBLES 
AS
BEGIN
    FOR categorias IN (SELECT descripcion FROM usuarioDondePapa.categoria WHERE disponible = 1) LOOP
        DBMS_OUTPUT.PUT_LINE('Categoría: ' || categorias.descripcion);
    END LOOP;
END;

BEGIN
    -- Ejecuta el procedimiento para obtener las categorías disponibles
    OBTENER_CATEGORIAS_DISPONIBLES;
END;
/
--------------------------------------------------------
--16.  Procedimiento para contar el número de platos por categoría

CREATE OR REPLACE PROCEDURE CONTAR_PLATOS_POR_CATEGORIA 
AS
BEGIN
    FOR categoria IN (SELECT c.descripcion, COUNT(p.id_plato) AS numero_platos 
                      FROM usuarioDondePapa.categoria c
                      JOIN usuarioDondePapa.plato p ON c.id_categoria = p.id_categoria
                      GROUP BY c.descripcion) LOOP
        DBMS_OUTPUT.PUT_LINE('Categoría: ' || categoria.descripcion || ', Número de Platos: ' || categoria.numero_platos);
    END LOOP;
END;

BEGIN
    -- Ejecuta el procedimiento para contar los platos por categoría
    CONTAR_PLATOS_POR_CATEGORIA;
END;
/

--------------------------------------------------------
--17. Procedimiento para insertar un nuevo usuario

CREATE OR REPLACE PROCEDURE INSERTAR_USUARIO (
    p_username IN VARCHAR2,
    p_password IN VARCHAR2,
    p_nombre IN VARCHAR2,
    p_apellidos IN VARCHAR2,
    p_correo IN VARCHAR2,
    p_telefono IN VARCHAR2,
    p_ruta_imagen IN VARCHAR2,
    p_activo IN NUMBER
) 
AS
BEGIN
    INSERT INTO usuarioDondePapa.usuario (username, password, nombre, apellidos, correo, telefono, ruta_imagen, activo)
    VALUES (p_username, p_password, p_nombre, p_apellidos, p_correo, p_telefono, p_ruta_imagen, p_activo);
END;
/

BEGIN
    -- Prueba del procedimiento insertando un nuevo usuario
    INSERTAR_USUARIO(
        'jdoe',                 -- Username del usuario
        'password123',          -- Contraseña del usuario
        'John',                 -- Nombre del usuario
        'Doe',                  -- Apellidos del usuario
        'john.doe@email.com',   -- Correo electrónico del usuario
        '555-1234',             -- Teléfono del usuario
        '/images/jdoe.png',     -- imagen del usuario
        1                       -- Activo (1 = sí, 0 = no)
    );
END;
/

SELECT * FROM usuarioDondePapa.usuario WHERE username = 'jdoe';

SELECT * FROM USUARIO;

BEGIN
    -- Prueba del procedimiento insertando un nuevo usuario
    INSERTAR_USUARIO(
        'JPeverest',                -- Username del usuario
        'password123',              -- Contraseña del usuario
        'Juan',                     -- Nombre del usuario
        'Perez',                    -- Apellido del usuario
        'juan.perez@email.com',     -- Correo electrónico del usuario
        '555-1234',                 -- Teléfono del usuario
        '/images/JPeverest.jpeg',   -- Contraseña del usuario
        1
    );
END;
/

SELECT * FROM usuarioDondePapa.usuario WHERE correo = 'juan.perez@email.com';

--------------------------------------------------------
--18. Procedimiento para eliminar una factura.
CREATE OR REPLACE PROCEDURE ELIMINAR_FACTURA (
    p_id_factura IN NUMBER
) 
AS
BEGIN
    -- Eliminar las ventas asociadas a la factura
    DELETE FROM usuarioDondePapa.venta
    WHERE id_factura = p_id_factura;

    -- Eliminar la factura
    DELETE FROM usuarioDondePapa.factura
    WHERE id_factura = p_id_factura;
END;

BEGIN
    -- Prueba del procedimiento eliminando una factura específica
    ELIMINAR_FACTURA(1); 
END;

--------------------------------------------------------
--19. Obtener Platos Más Vendidos
CREATE OR REPLACE PROCEDURE OBTENER_PLATOS_MAS_VENDIDOS 
AS
BEGIN
    FOR grupo_platos IN (
        SELECT p.descripcion, SUM(v.cantidad) AS total_vendido
        FROM plato p
        JOIN venta v ON p.id_plato = v.id_plato
        GROUP BY p.descripcion
        ORDER BY total_vendido DESC
    )
    LOOP
        DBMS_OUTPUT.PUT_LINE('Plato: ' || grupo_platos.descripcion || ', Total vendido: ' || grupo_platos.total_vendido);
    END LOOP;
END;

-------------------------------------------------------
--20. Obtener usuario más activos
CREATE OR REPLACE PROCEDURE OBTENER_USUARIO_MAS_ACTIVO
AS
    nombre USUARIO.NOMBRE%TYPE;
	apellidos USUARIO.APELLIDOS%TYPE;
	total_compras NUMBER;
BEGIN
   SELECT nombre, apellidos, count_compras
    INTO nombre, apellidos, total_compras
    FROM (
        SELECT u.nombre, u.apellidos, COUNT(f.id_factura) AS count_compras
        FROM usuario u
        JOIN factura f ON u.id_usuario = f.id_usuario
        GROUP BY u.nombre, u.apellidos
        ORDER BY count_compras DESC
    )
    WHERE ROWNUM = 1;

    DBMS_OUTPUT.PUT_LINE('Usuario: ' || nombre || ' ' || apellidos || ', Total compras: ' || total_compras);
END;

-------------------------------------------------------
--21. Generar reportes de ventas por categoría
CREATE OR REPLACE PROCEDURE REPORTE_VENTAS_POR_CATEGORIAS
AS
BEGIN
    FOR grupo_categorias IN (
        SELECT c.descripcion, SUM(v.cantidad * v.precio) AS total_ventas
        FROM categoria c
        JOIN plato p ON c.id_categoria = p.id_categoria
        JOIN venta v ON p.id_plato = v.id_plato
        GROUP BY c.descripcion
        ORDER BY total_ventas DESC
    )
    LOOP
        DBMS_OUTPUT.PUT_LINE('Categoría: ' || grupo_categorias.descripcion || ', Total ventas: ' || grupo_categorias.total_ventas);
    END LOOP;
END;

-------------------------------------------------------
--22. Restablecer contraseña de usuario
CREATE OR REPLACE PROCEDURE restablecer_contrasena (
    v_usuario VARCHAR2,
    p_nueva_contrasena VARCHAR2
)
AS
BEGIN
    UPDATE usuario
    SET password = p_nueva_contrasena
    WHERE username = v_usuario;
END;

BEGIN
    restablecer_contrasena('allan','12345');
END;

-------------------------------------------------------
--23. Modificar una reserva
CREATE OR REPLACE PROCEDURE modificar_reserva (
    id_reservacion_modificar NUMBER,
    nueva_hora TIMESTAMP,
    nuevo_numero_mesa NUMBER
)
AS
	mesa_disponible NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO mesa_disponible
    FROM reservacion
    WHERE numero_de_mesa = nuevo_numero_mesa 
    AND hora = nueva_hora;

	IF mesa_disponible > 0 THEN
    	RAISE_APPLICATION_ERROR(-20101, 'No se puede modificar la reservacion, porque ya existe una reservacion en ese horario');
	ELSE 
        UPDATE reservacion
    	SET hora = nueva_hora, numero_de_mesa = nuevo_numero_mesa
    	WHERE id_reservacion = id_reservacion_modificar;
    END IF;
END;

BEGIN
    modificar_reserva(1,TO_TIMESTAMP('2024-07-01 13:00:00', 'YYYY-MM-DD HH24:MI:SS'),2);
END;

-------------------------------------------------------
--24. Obtener disponibilidad de mesas
CREATE OR REPLACE PROCEDURE obtener_disponibilidad_mesas (
    p_hora TIMESTAMP
)
AS
BEGIN
    FOR v_mesa IN (
        SELECT numero_de_mesa
        FROM mesa
        WHERE numero_de_mesa NOT IN (
            SELECT numero_de_mesa
            FROM reservacion
            WHERE hora BETWEEN p_hora - INTERVAL '1' HOUR AND p_hora + INTERVAL '1' HOUR
        )
    )
    LOOP
        DBMS_OUTPUT.PUT_LINE('Mesa disponible: ' || v_mesa.numero_de_mesa);
    END LOOP;
END;

-------------------------------------------------------
--25. Actualizar salarios en base a la cantidad de años laborados
CREATE OR REPLACE PROCEDURE actualizar_salario_por_antiguedad
IS
BEGIN
    UPDATE employees
    SET salary = salary * 1.05
    WHERE (SYSDATE - hire_date) / 365 BETWEEN 1 AND 5;

    UPDATE employees
    SET salary = salary * 1.10
    WHERE (SYSDATE - hire_date) / 365 BETWEEN 6 AND 10;

    UPDATE employees
    SET salary = salary * 1.15
    WHERE (SYSDATE - hire_date) / 365 > 10;
    
    DBMS_OUTPUT.PUT_LINE('Salarios actualizados en función de los años de servicio.');
END;

--------------------------------------------------------
-- VISTAS
--------------------------------------------------------

// 1. Mostrar todos los platos disponibles por categoria a la que pertencen
CREATE OR REPLACE VIEW usuarioDondePapa.vista_platos_disponibles AS
SELECT 
    p.id_plato,
    p.descripcion AS plato_descripcion,
    p.detalle,
    p.precio,
    p.existencias,
    p.ruta_imagen,
    c.descripcion AS categoria_descripcion,
    p.disponible
FROM 
    usuarioDondePapa.plato p
JOIN 
    usuarioDondePapa.categoria c ON p.id_categoria = c.id_categoria
WHERE 
    p.disponible = 1;
    
--------------------------------------------------------

// 2. Muestra informacion adicional sobre los usuarios que las realizaron.informaci?n adicional sobre los usuarios que las realizaron.
CREATE OR REPLACE VIEW usuarioDondePapa.vista_facturas_con_usuarios AS
SELECT 
    f.id_factura,
    f.fecha,
    f.total,
    f.estado,
    u.nombre,
    u.apellidos,
    u.correo,
    u.telefono
FROM 
    usuarioDondePapa.factura f
JOIN 
    usuarioDondePapa.usuario u ON f.id_usuario = u.id_usuario;
    
--------------------------------------------------------
    
// 3. Esta vista muestra las ventas realizadas, incluyendo informaci?n del plato vendido y la factura asociada.
CREATE OR REPLACE VIEW usuarioDondePapa.vista_ventas_detalles AS
SELECT 
    v.id_venta,
    f.fecha,
    p.descripcion AS plato_descripcion,
    p.precio,
    v.cantidad,
    v.precio AS precio_venta,
    f.total AS total_factura
FROM 
    usuarioDondePapa.venta v
JOIN 
    usuarioDondePapa.factura f ON v.id_factura = f.id_factura
JOIN 
    usuarioDondePapa.plato p ON v.id_plato = p.id_plato;

--------------------------------------------------------

// 4. Esta vista muestra los usuarios junto con los roles asignados a cada uno.
CREATE OR REPLACE VIEW usuarioDondePapa.vista_usuarios_roles AS
SELECT 
    u.id_usuario,
    u.username,
    u.nombre,
    u.apellidos,
    r.nombre AS rol
FROM 
    usuarioDondePapa.usuario u
JOIN 
    usuarioDondePapa.rol r ON u.id_usuario = r.id_usuario;

--------------------------------------------------------

// 5. Esta vista muestra todas las reservaciones con informaci?n de contacto.
CREATE OR REPLACE VIEW usuarioDondePapa.vista_reservaciones AS
SELECT 
    r.id_reservacion,
    r.nombre,
    r.hora,
    r.numero_de_mesa,
    r.contacto
FROM 
    usuarioDondePapa.reservacion r;
--------------------------------------------------------
// 6. Esta vista muestra los ingresos diarios del restaurante, agrupados por fecha.

CREATE OR REPLACE VIEW usuarioDondePapa.vista_ingresos_diarios AS
SELECT 
    TO_CHAR(f.fecha, 'YYYY-MM-DD') AS fecha,
    SUM(f.total) AS total_ingresos
FROM 
    usuarioDondePapa.factura f
GROUP BY 
    TO_CHAR(f.fecha, 'YYYY-MM-DD')
ORDER BY 
    fecha DESC;


--------------------------------------------------------
//  7. Esta vista muestra los platos más vendidos, ordenados por la cantidad vendida.
CREATE OR REPLACE VIEW usuarioDondePapa.vista_top_platos_vendidos AS
SELECT 
    p.id_plato,
    p.descripcion AS plato_descripcion,
    SUM(v.cantidad) AS total_vendido
FROM 
    usuarioDondePapa.venta v
JOIN 
    usuarioDondePapa.plato p ON v.id_plato = p.id_plato
GROUP BY 
    p.id_plato, p.descripcion
ORDER BY 
    total_vendido DESC;
--------------------------------------------------------
//8. Esta vista muestra a los clientes más frecuentes, ordenados por el número de facturas emitidas a su nombre.
CREATE OR REPLACE VIEW usuarioDondePapa.vista_clientes_frecuentes AS
SELECT 
    u.id_usuario,
    u.nombre,
    u.apellidos,
    COUNT(f.id_factura) AS total_facturas
FROM 
    usuarioDondePapa.usuario u
JOIN 
    usuarioDondePapa.factura f ON u.id_usuario = f.id_usuario
GROUP BY 
    u.id_usuario, u.nombre, u.apellidos
ORDER BY 
    total_facturas DESC;
    
--------------------------------------------------------
// 9. Esta vista muestra todos los productos (platos) que actualmente no tienen existencias disponibles.
CREATE OR REPLACE VIEW usuarioDondePapa.vista_productos_no_disponibles AS
SELECT 
    p.id_plato,
    p.descripcion AS plato_descripcion,
    p.detalle,
    p.precio,
    p.ruta_imagen,
    c.descripcion AS categoria_descripcion
FROM 
    usuarioDondePapa.plato p
JOIN 
    usuarioDondePapa.categoria c ON p.id_categoria = c.id_categoria
WHERE 
    p.existencias = 0 
    OR p.disponible = 0
ORDER BY 
    p.descripcion ASC;

--------------------------------------------------------
// 10. Esta vista muestra los usuarios que tienen facturas pendientes de pago.
CREATE OR REPLACE VIEW usuarioDondePapa.vista_categorias_mas_vendidas AS
SELECT 
    c.id_categoria,
    c.descripcion AS categoria_descripcion,
    SUM(v.cantidad) AS total_vendido,
    SUM(v.precio * v.cantidad) AS ingresos_generados
FROM 
    usuarioDondePapa.categoria c
JOIN 
    usuarioDondePapa.plato p ON c.id_categoria = p.id_categoria
JOIN 
    usuarioDondePapa.venta v ON p.id_plato = v.id_plato
GROUP BY 
    c.id_categoria, c.descripcion
ORDER BY 
    total_vendido DESC;

--------------------------------------------------------
-- TRIGGERS
--------------------------------------------------------
-- 1. Trigger para controlar existencias de platos

CREATE OR REPLACE TRIGGER trg_plato_update_stock
  AFTER INSERT OR UPDATE OR DELETE
  ON venta
  FOR EACH ROW
BEGIN
  UPDATE PLATO
  SET EXISTENCIAS = EXISTENCIAS - :NEW.CANTIDAD
  WHERE ID_PLATO = :NEW.ID_PLATO;
END;

SELECT * FROM PLATO WHERE id_plato=5;
INSERT INTO venta (id_factura, id_plato, precio, cantidad) VALUES (3, 5, 45000, 3);

--------------------------------------------------------
-- 2. Trigger para controlar las ventas de platos segun stock

CREATE OR REPLACE TRIGGER trg_verificar_stock
  BEFORE INSERT OR UPDATE ON venta
  FOR EACH ROW
DECLARE
  cantidad_en_stock NUMBER;
BEGIN
  SELECT EXISTENCIAS INTO cantidad_en_stock
  FROM plato
  WHERE id_plato = :NEW.id_plato;

  IF :NEW.cantidad > cantidad_en_stock THEN
    RAISE_APPLICATION_ERROR(-20001, 'No hay suficientes platos en stock para completar la venta.');
  END IF;
END;

SELECT * FROM PLATO WHERE id_plato=4;
INSERT INTO venta (id_factura, id_plato, precio, cantidad) VALUES (3, 4, 45000, 8);
UPDATE plato
SET existencias = 10 WHERE id_plato = 4;

--------------------------------------------------------
-- 3. Trigger para registrar transacciones de facturas en estado 1

CREATE OR REPLACE TRIGGER TRG_FACTURA_TRANSACCION
  AFTER INSERT OR UPDATE OF ESTADO
  ON FACTURA
  FOR EACH ROW
BEGIN
  IF :new.ESTADO = 1 THEN
    INSERT INTO TRANSACCIONES (
      ID_USUARIO,
      TIPO,
      MONTO,
      FECHA,
      DESCRIPCION
    )
    VALUES (
      :new.ID_USUARIO,
      'VENTA', -- Puedes ajustar el tipo según tus necesidades
      :new.TOTAL,
      SYSTIMESTAMP,
      'Factura ' || :new.ID_FACTURA
    );
  END IF;
END;

SELECT * FROM factura;
SELECT * FROM transacciones;
UPDATE FACTURA
SET ESTADO = 1
WHERE ID_FACTURA=1;

--------------------------------------------------------
-- 4. Trigger auditoria de reservaciones eliminadas

CREATE TABLE RESERVACION_AUDIT (
  ID_AUDITORIA NUMBER GENERATED BY DEFAULT AS IDENTITY,
  ID_RESERVACION NUMBER,
  NOMBRE VARCHAR2(255),
  HORA TIMESTAMP(6),
  NUMERO_DE_MESA NUMBER,
  CONTACTO VARCHAR2(255),
  FECHA_ELIMINACION TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE OR REPLACE TRIGGER TRG_RESERVACION_DELETE
  AFTER DELETE
  ON RESERVACION
  FOR EACH ROW
BEGIN
  INSERT INTO RESERVACION_AUDIT (
    ID_RESERVACION,
    NOMBRE,
    HORA,
    NUMERO_DE_MESA,
    CONTACTO,
    FECHA_ELIMINACION
  )
  VALUES (
    :OLD.ID_RESERVACION,
    :OLD.NOMBRE,
    :OLD.HORA,
    :OLD.NUMERO_DE_MESA,
    :OLD.CONTACTO,
    SYSTIMESTAMP
  );
END;

SELECT * FROM reservacion;
DELETE reservacion WHERE id_reservacion=2;
SELECT * FROM RESERVACION_AUDIT;

--------------------------------------------------------
-- 5. Trigger para evitar una reservacion si choca con otros horarios

CREATE OR REPLACE TRIGGER TRG_RESERVACION_UNIQUE
  BEFORE INSERT OR UPDATE
  ON RESERVACION
  FOR EACH ROW
DECLARE
  count_reservaciones NUMBER;
BEGIN
  SELECT COUNT(*) 
  INTO count_reservaciones
  FROM RESERVACION
  WHERE NUMERO_DE_MESA = :new.NUMERO_DE_MESA
  AND HORA = :new.HORA;

  IF count_reservaciones > 0 THEN
    RAISE_APPLICATION_ERROR(-20005, 'Ya existe una reserva para esa mesa y hora.');
  END IF;
END;

SELECT * FROM reservacion;

-- Reserva válida
BEGIN
    INSERT INTO RESERVACION (nombre, hora, numero_de_mesa, contacto)
    VALUES ('John Doe', TO_DATE('2024-08-25 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 5, '555-1234');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Inserción 1 fallida: ' || SQLERRM);
END;

--Reserva invalida
BEGIN
    INSERT INTO RESERVACION (nombre, hora, numero_de_mesa, contacto)
    VALUES ('Jane Smith', TO_DATE('2024-08-25 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 5, '555-5678');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Inserción 2 fallida: ' || SQLERRM);
END;

--------------------------------------------------------
-- CURSORES
--------------------------------------------------------

// 1.
CREATE OR REPLACE PROCEDURE OBTENER_PLATOS_DISPONIBLES 
AS
    CURSOR platos_disponibles_cur IS
        SELECT descripcion FROM usuarioDondePapa.plato WHERE disponible = 1;
    v_descripcion usuarioDondePapa.plato.descripcion%TYPE;
BEGIN
    OPEN platos_disponibles_cur;
    LOOP
        FETCH platos_disponibles_cur INTO v_descripcion;
        EXIT WHEN platos_disponibles_cur%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('Plato: ' || v_descripcion);
    END LOOP;
    CLOSE platos_disponibles_cur;
END;

BEGIN
    OBTENER_PLATOS_DISPONIBLES;
END;
--------------------------------------------------------

// 2.
CREATE OR REPLACE PROCEDURE OBTENER_FACTURAS_POR_USUARIO (
    id_usuario IN NUMBER
) 
AS
    CURSOR facturas_cur IS
        SELECT * FROM usuarioDondePapa.factura WHERE id_usuario = id_usuario;
    v_factura usuarioDondePapa.factura%ROWTYPE;
BEGIN
    OPEN facturas_cur;
    LOOP
        FETCH facturas_cur INTO v_factura;
        EXIT WHEN facturas_cur%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Factura: ' || v_factura.id_factura || ', Fecha: ' || v_factura.fecha || ', Total: ' || v_factura.total || ', Estado: ' || v_factura.estado);
    END LOOP;
    CLOSE facturas_cur;
END;

BEGIN
    OBTENER_FACTURAS_POR_USUARIO(1);  -- ACA SE CAMBIA POR EL VALOR DE USER
END;
--------------------------------------------------------

// 3.
CREATE OR REPLACE PROCEDURE OBTENER_VENTAS_POR_PLATO (
    id_plato IN NUMBER
) 
AS
    CURSOR ventas_cur IS
        SELECT * FROM usuarioDondePapa.venta WHERE id_plato = id_plato;
    v_venta usuarioDondePapa.venta%ROWTYPE;
BEGIN
    OPEN ventas_cur;
    LOOP
        FETCH ventas_cur INTO v_venta;
        EXIT WHEN ventas_cur%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Venta: ' || v_venta.id_venta || ', ID Factura: ' || v_venta.id_factura || ', Precio: ' || v_venta.precio || ', Cantidad: ' || v_venta.cantidad);
    END LOOP;
    CLOSE ventas_cur;
END;

BEGIN
    OBTENER_VENTAS_POR_PLATO(2);  -- SE CAMBIA POR EL ID
END;

--------------------------------------------------------

// 4
CREATE OR REPLACE PROCEDURE OBTENER_TOTAL_VENTAS_POR_USUARIO (
    id_usuario IN NUMBER
) 
AS
    CURSOR ventas_total_cur IS
        SELECT f.id_usuario, SUM(v.precio * v.cantidad) AS total_ventas
        FROM usuarioDondePapa.venta v
        JOIN usuarioDondePapa.factura f ON v.id_factura = f.id_factura
        WHERE f.id_usuario = id_usuario
        GROUP BY f.id_usuario;
    v_id_usuario usuarioDondePapa.factura.id_usuario%TYPE;
    v_total_ventas NUMBER;
BEGIN
    OPEN ventas_total_cur;
    LOOP
        FETCH ventas_total_cur INTO v_id_usuario, v_total_ventas;
        EXIT WHEN ventas_total_cur%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Usuario: ' || v_id_usuario || ', Total Ventas: ' || v_total_ventas);
    END LOOP;
    CLOSE ventas_total_cur;
END;

BEGIN
    OBTENER_TOTAL_VENTAS_POR_USUARIO(1);  -- CAMBIAR POR USER
END;

--------------------------------------------------------

// 5.
CREATE OR REPLACE PROCEDURE OBTENER_RESERVACIONES (
    id_reservacion IN NUMBER
) 
AS
    CURSOR reservaciones_cur IS
        SELECT * FROM usuarioDondePapa.reservacion WHERE id_reservacion = id_reservacion;
    v_reservacion usuarioDondePapa.reservacion%ROWTYPE;
BEGIN
    OPEN reservaciones_cur;
    LOOP
        FETCH reservaciones_cur INTO v_reservacion;
        EXIT WHEN reservaciones_cur%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Reservacion: ' || v_reservacion.id_reservacion || ', Nombre: ' || v_reservacion.nombre || ', Hora: ' || v_reservacion.hora || ', Numero de Mesa: ' || v_reservacion.numero_de_mesa || ', Contacto: ' || v_reservacion.contacto);
    END LOOP;
    CLOSE reservaciones_cur;
END;

BEGIN
    OBTENER_RESERVACIONES(101);  -- CAMBIAR POR ID RESERVACION
END;

--------------------------------------------------------

// 6.
CREATE OR REPLACE PROCEDURE OBTENER_CLIENTES_POR_ESTADO (
    estado IN NUMBER
) 
AS
    CURSOR clientes_cursor IS
        SELECT ID_USUARIO, NOMBRE, CORREO
        FROM USUARIODONDEPAPA.USUARIO
        WHERE ACTIVO = estado;
    
    cliente_record clientes_cursor%ROWTYPE;
BEGIN
    OPEN clientes_cursor;
    LOOP
        FETCH clientes_cursor INTO cliente_record;
        EXIT WHEN clientes_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Usuario: ' || cliente_record.ID_USUARIO || ', Nombre: ' || cliente_record.NOMBRE || ', Correo: ' || cliente_record.CORREO);
    END LOOP;
    CLOSE clientes_cursor;
END;

BEGIN
    OBTENER_CLIENTES_POR_ESTADO(1);  -- CAMBIAR POR EL ESTADO
END;

--------------------------------------------------------

// 7.
CREATE OR REPLACE PROCEDURE OBTENER_PRODUCTOS_POR_CATEGORIA (
    id_categoria IN NUMBER
) 
AS
    CURSOR productos_cursor IS
        SELECT ID_PLATO, DESCRIPCION, PRECIO
        FROM USUARIODONDEPAPA.PLATO
        WHERE ID_CATEGORIA = id_categoria;
    
    producto_record productos_cursor%ROWTYPE;
BEGIN
    OPEN productos_cursor;
    LOOP
        FETCH productos_cursor INTO producto_record;
        EXIT WHEN productos_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Plato: ' || producto_record.ID_PLATO || ', DescripciÃ³n: ' || producto_record.DESCRIPCION || ', Precio: ' || producto_record.PRECIO);
    END LOOP;
    CLOSE productos_cursor;
END;

BEGIN
    OBTENER_PRODUCTOS_POR_CATEGORIA(2);  -- CAMBIAR ID POR CATEGORIA
END;

--------------------------------------------------------
// 8.
CREATE OR REPLACE PROCEDURE OBTENER_RESERVAS_POR_FECHA (
    fecha IN DATE
) 
AS
    CURSOR reservas_cursor IS
        SELECT ID_RESERVACION, NOMBRE, HORA, NUMERO_DE_MESA
        FROM USUARIODONDEPAPA.RESERVACION
        WHERE TRUNC(HORA) = fecha;
    
    reserva_record reservas_cursor%ROWTYPE;
BEGIN
    OPEN reservas_cursor;
    LOOP
        FETCH reservas_cursor INTO reserva_record;
        EXIT WHEN reservas_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Reserva: ' || reserva_record.ID_RESERVACION || ', Nombre: ' || reserva_record.NOMBRE || ', Hora: ' || reserva_record.HORA || ', Número de Mesa: ' || reserva_record.NUMERO_DE_MESA);
    END LOOP;
    CLOSE reservas_cursor;
END;

BEGIN
    OBTENER_RESERVAS_POR_FECHA(TO_DATE('2024-07-1', 'YYYY-MM-DD')); -- CAMBIAR FECHA DEFAUL
END;

--------------------------------------------------------
//9.
CREATE OR REPLACE PROCEDURE OBTENER_VENTAS_POR_FECHA (
    fecha IN DATE
) 
AS
    CURSOR ventas_cursor IS
        SELECT ID_VENTA, ID_PLATO, CANTIDAD, PRECIO
        FROM USUARIODONDEPAPA.VENTA
        WHERE EXISTS (
            SELECT 1
            FROM USUARIODONDEPAPA.FACTURA
            WHERE FACTURA.ID_FACTURA = VENTA.ID_FACTURA
            AND TRUNC(FACTURA.FECHA) = fecha
        );
    
    venta_record ventas_cursor%ROWTYPE;
BEGIN
    OPEN ventas_cursor;
    LOOP
        FETCH ventas_cursor INTO venta_record;
        EXIT WHEN ventas_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Venta: ' || venta_record.ID_VENTA || ', ID Plato: ' || venta_record.ID_PLATO || ', Cantidad: ' || venta_record.CANTIDAD || ', Precio: ' || venta_record.PRECIO);
    END LOOP;
    CLOSE ventas_cursor;
END;

BEGIN
    OBTENER_VENTAS_POR_FECHA(TO_DATE('2024-08-21', 'YYYY-MM-DD'));-- CAMBIAR FECHA
END;

--------------------------------------------------------
// 10.
CREATE OR REPLACE PROCEDURE OBTENER_FACTURAS_POR_ESTADO (
    estado IN NUMBER
) 
AS
    CURSOR facturas_cursor IS
        SELECT ID_FACTURA, FECHA, TOTAL
        FROM USUARIODONDEPAPA.FACTURA
        WHERE ESTADO = estado;
    
    factura_record facturas_cursor%ROWTYPE;
BEGIN
    OPEN facturas_cursor;
    LOOP
        FETCH facturas_cursor INTO factura_record;
        EXIT WHEN facturas_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Factura: ' || factura_record.ID_FACTURA || ', Fecha: ' || factura_record.FECHA || ', Total: ' || factura_record.TOTAL);
    END LOOP;
    CLOSE facturas_cursor;
END;

BEGIN
    OBTENER_FACTURAS_POR_ESTADO(1);  -- CAMBIAR ID POR ESTADO
END;

--------------------------------------------------------
// 11.
CREATE OR REPLACE PROCEDURE OBTENER_TRANSACCIONES_POR_TIPO (
    tipo_transaccion IN VARCHAR2
) 
AS
    CURSOR transacciones_cursor IS
        SELECT ID_TRANSACCION, MONTO, FECHA, DESCRIPCION
        FROM USUARIODONDEPAPA.TRANSACCIONES
        WHERE TIPO = tipo_transaccion;
    
    transaccion_record transacciones_cursor%ROWTYPE;
BEGIN
    OPEN transacciones_cursor;
    LOOP
        FETCH transacciones_cursor INTO transaccion_record;
        EXIT WHEN transacciones_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Transacción: ' || transaccion_record.ID_TRANSACCION || ', Monto: ' || transaccion_record.MONTO || ', Fecha: ' || transaccion_record.FECHA || ', Descripción: ' || transaccion_record.DESCRIPCION);
    END LOOP;
    CLOSE transacciones_cursor;
END;

BEGIN
    OBTENER_TRANSACCIONES_POR_TIPO('Pago');  -- CAMBIAR POR EL TIPO DE TRANSACCIONS
END;

--------------------------------------------------------
// 12.
CREATE OR REPLACE PROCEDURE OBTENER_USUARIOS_ACTIVOS
AS
    CURSOR usuarios_cursor IS
        SELECT ID_USUARIO, NOMBRE, CORREO
        FROM USUARIODONDEPAPA.USUARIO
        WHERE ACTIVO = 1;
    
    usuario_record usuarios_cursor%ROWTYPE;
BEGIN
    OPEN usuarios_cursor;
    LOOP
        FETCH usuarios_cursor INTO usuario_record;
        EXIT WHEN usuarios_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Usuario: ' || usuario_record.ID_USUARIO || ', Nombre: ' || usuario_record.NOMBRE || ', Correo: ' || usuario_record.CORREO);
    END LOOP;
    CLOSE usuarios_cursor;
END;

BEGIN
    OBTENER_USUARIOS_ACTIVOS;
END;

--------------------------------------------------------
// 13.
CREATE OR REPLACE PROCEDURE OBTENER_PLATOS_DISPONIBLES
AS
    CURSOR platos_cursor IS
        SELECT ID_PLATO, DESCRIPCION, PRECIO, EXISTENCIAS
        FROM USUARIODONDEPAPA.PLATO
        WHERE DISPONIBLE = 1;
    
    plato_record platos_cursor%ROWTYPE;
BEGIN
    OPEN platos_cursor;
    LOOP
        FETCH platos_cursor INTO plato_record;
        EXIT WHEN platos_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Plato: ' || plato_record.ID_PLATO || ', Descripción: ' || plato_record.DESCRIPCION || ', Precio: ' || plato_record.PRECIO || ', Existencias: ' || plato_record.EXISTENCIAS);
    END LOOP;
    CLOSE platos_cursor;
END;

BEGIN
    OBTENER_PLATOS_DISPONIBLES;
END;

--------------------------------------------------------
// 14.
CREATE OR REPLACE PROCEDURE OBTENER_FACTURAS_POR_USUARIO (
    id_usuario IN NUMBER
) 
AS
    CURSOR facturas_cursor IS
        SELECT ID_FACTURA, FECHA, TOTAL, ESTADO
        FROM USUARIODONDEPAPA.FACTURA
        WHERE ID_USUARIO = id_usuario;
    
    factura_record facturas_cursor%ROWTYPE;
BEGIN
    OPEN facturas_cursor;
    LOOP
        FETCH facturas_cursor INTO factura_record;
        EXIT WHEN facturas_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Factura: ' || factura_record.ID_FACTURA || ', Fecha: ' || factura_record.FECHA || ', Total: ' || factura_record.TOTAL || ', Estado: ' || factura_record.ESTADO);
    END LOOP;
    CLOSE facturas_cursor;
END;

BEGIN
    OBTENER_FACTURAS_POR_USUARIO(:id_usuario);
END;

--------------------------------------------------------
// 15.
CREATE OR REPLACE PROCEDURE OBTENER_RESERVAS_POR_NOMBRE (
    nombre_cliente IN VARCHAR2
) 
AS
    CURSOR reservas_cursor IS
        SELECT ID_RESERVACION, HORA, NUMERO_DE_MESA, CONTACTO
        FROM USUARIODONDEPAPA.RESERVACION
        WHERE NOMBRE = nombre_cliente;
    
    reserva_record reservas_cursor%ROWTYPE;
BEGIN
    OPEN reservas_cursor;
    LOOP
        FETCH reservas_cursor INTO reserva_record;
        EXIT WHEN reservas_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Reservación: ' || reserva_record.ID_RESERVACION || ', Hora: ' || reserva_record.HORA || ', Número de Mesa: ' || reserva_record.NUMERO_DE_MESA || ', Contacto: ' || reserva_record.CONTACTO);
    END LOOP;
    CLOSE reservas_cursor;
END;


BEGIN
    OBTENER_RESERVAS_POR_NOMBRE('Juan');
END;
--------------------------------------------------------
-- FUNCIONES & PAQUETES
--------------------------------------------------------

-- 1. Obtener platos por categoría especificada.

CREATE OR REPLACE FUNCTION OBTENER_PLATOS_X_CATEGORIA (
    id_categoria NUMBER -- Dependiendo del valor de la categoria, se mostrarán x platos que pertenezcan a la misma.
)
RETURN SYS_REFCURSOR
AS
    platos_cursor SYS_REFCURSOR;
BEGIN
    OPEN platos_cursor FOR -- Se abre el cursor que empieza a obtener los datos.
        SELECT ruta_imagen, precio, descripcion, detalle -- Selecciona las columnas.
        FROM usuarioDondePapa.PLATO -- De la tabla PLATO.
        WHERE id_categoria = id_categoria;  -- Donde todos coincidan con el mismo ID de categoría.
    RETURN platos_cursor; -- Y retorna el cursor con los datos para ser visualizados.
END;

DECLARE
    v_cursor SYS_REFCURSOR;
    v_ruta_imagen usuarioDondePapa.PLATO.ruta_imagen%TYPE;
    v_precio usuarioDondePapa.PLATO.precio%TYPE;
    v_descripcion usuarioDondePapa.PLATO.descripcion%TYPE;
    v_detalle usuarioDondePapa.PLATO.detalle%TYPE;
BEGIN
    v_cursor := OBTENER_PLATOS_X_CATEGORIA(2);
    
    LOOP
        FETCH v_cursor INTO v_ruta_imagen, v_precio, v_descripcion, v_detalle;
        EXIT WHEN v_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('Descripción: ' || v_descripcion || CHR(10) ||
    'Precio: ' || v_precio || CHR(10) || 
    'Detalle: ' || v_detalle || CHR(10) ||
    'Ruta Imagen: ' || v_ruta_imagen || CHR(10));
    END LOOP;
    CLOSE v_cursor;
END;

SELECT * FROM PLATO;

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

-- 2. Obtener el total de un producto, el total con descuento aplicado, y el monto reducido con el descuento.
CREATE OR REPLACE FUNCTION CALCULAR_DESCUENTO_PLATO (
    p_id_plato IN NUMBER,
    p_descuento_porcentaje IN NUMBER
)
RETURN NUMBER
AS
    v_precio_plato usuarioDondePapa.plato.precio%TYPE;
    v_precio_descuento NUMBER;
BEGIN
    SELECT precio INTO v_precio_plato
    FROM usuarioDondePapa.plato
    WHERE id_plato = p_id_plato;
    
    v_precio_descuento := v_precio_plato - (v_precio_plato * (p_descuento_porcentaje / 100));
    
    RETURN v_precio_descuento;
END;

SELECT p.id_plato "ID", p.precio "Precio Original", 
    CALCULAR_DESCUENTO_PLATO(p.id_plato, 10) "Precio con Descuento",
    (p.precio - CALCULAR_DESCUENTO_PLATO(p.id_plato, 10)) "Descuento"
FROM PLATO p
WHERE p.id_plato = 45;

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

-- 3. Función para verificar si una mesa está apartada o reservada, esto 
-- introduciendo el número de la mesa y la fecha del día de la reserva.
-- **ABIERTO A MEJORAS **
CREATE OR REPLACE FUNCTION VERIFICAR_DISPONIBILIDAD_MESA (  
    p_numero_mesa IN NUMBER,
    p_fecha IN DATE
)
RETURN VARCHAR2
IS
    v_contador NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_contador
    FROM RESERVACION
    WHERE numero_de_mesa = p_numero_mesa
    AND TRUNC(hora) = p_fecha;
    
    IF v_contador > 0 THEN
        return 'APARTADA';
    ELSE
        return 'DISPONIBLE';
    END IF;
END;

SELECT * FROM RESERVACION;

SELECT VERIFICAR_DISPONIBILIDAD_MESA(3, TO_DATE('01-JUL-24', 'DD-MON-YY')) Disponibilidad
FROM DUAL;

SELECT VERIFICAR_DISPONIBILIDAD_MESA(5, TO_DATE('01-JUL-24', 'DD-MON-YY')) Disponibilidad
FROM DUAL;

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

-- 4. Función para encontrar el correo afiliado a un usuario específico por medio de su ID.
CREATE OR REPLACE FUNCTION OBTENER_CORREO_USUARIO (
    p_id_usuario IN NUMBER
)
RETURN VARCHAR2
IS
    v_correo VARCHAR2(100);
BEGIN
    SELECT CORREO
    INTO v_correo
    FROM USUARIO
    WHERE ID_USUARIO = p_id_usuario;
    
    RETURN v_correo;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'No se encontró un correo afiliado';
END;

SELECT username, correo FROM USUARIO;

SELECT OBTENER_CORREO_USUARIO(2) Correo FROM DUAL;
SELECT OBTENER_CORREO_USUARIO(7) Correo FROM DUAL;

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

-- 5. Función para obtener el nombre de un plato dependiendo del ID insertado
CREATE OR REPLACE FUNCTION OBTENER_PLATO_X_ID (
    p_id_plato IN NUMBER
) RETURN VARCHAR2
IS
    v_plato VARCHAR2(50);
BEGIN
    SELECT DESCRIPCION
    INTO v_plato
    FROM PLATO
    WHERE ID_PLATO = p_id_plato;
    
    RETURN v_plato;
EXCEPTION 
    WHEN NO_DATA_FOUND THEN
        RETURN 'No encontramos ese plato';
END;

DROP FUNCTION OBTENER_PLATO_X_ID;

SELECT id_plato, descripcion FROM PLATO;

SELECT OBTENER_PLATO_X_ID(42) Plato FROM DUAL;
SELECT OBTENER_PLATO_X_ID(85) Plato FROM DUAL;

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

-- 6. Funcion para mostrar el precio total de una factura con el IVA aplicado.
CREATE OR REPLACE FUNCTION CALCULAR_IVA_FACTURA (
    p_id_factura IN NUMBER
) RETURN NUMBER
IS
    v_total_factura NUMBER;
    v_iva NUMBER(5,2);
BEGIN
    v_iva := 0.13;
    
    SELECT TOTAL
    INTO v_total_factura
    FROM FACTURA
    WHERE ID_FACTURA = p_id_factura;
    
    RETURN v_total_factura * v_iva;
END;

SELECT f.total TOTAL, CALCULAR_IVA_FACTURA(3) TOTAL_IVA, '13%' AS IVA
FROM FACTURA f
WHERE f.id_factura = 3;

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

-- 7. Función que muestra por medio de DBMS.OUTPUT, una lista de las transacciones
-- realizadas por un usuario.
INSERT INTO usuarioDondePapa.transacciones (id_usuario, tipo, monto, fecha, descripcion)
    VALUES (1, 'Compra', 45.50, TO_DATE('2024-08-15', 'YYYY-MM-DD'), 'Compra de platos.');
INSERT INTO usuarioDondePapa.transacciones (id_usuario, tipo, monto, fecha, descripcion)
    VALUES (2, 'Pago de factura', 120.00, TO_DATE('2024-08-16', 'YYYY-MM-DD'), 'Pago de factura 123.');
INSERT INTO usuarioDondePapa.transacciones (id_usuario, tipo, monto, fecha, descripcion)
    VALUES (3, 'Reembolso', 30.00, TO_DATE('2024-08-17', 'YYYY-MM-DD'), 'Reembolso de reserva.');
INSERT INTO usuarioDondePapa.transacciones (id_usuario, tipo, monto, fecha, descripcion)
    VALUES (1, 'Compra', 75.00, TO_DATE('2024-08-18', 'YYYY-MM-DD'), 'Compra de comida para evento.');
INSERT INTO usuarioDondePapa.transacciones (id_usuario, tipo, monto, fecha, descripcion)
    VALUES (2, 'Compra', 50.00, TO_DATE('2024-08-20', 'YYYY-MM-DD'), 'Compra de bebidas.');
INSERT INTO usuarioDondePapa.transacciones (id_usuario, tipo, monto, fecha, descripcion)
    VALUES (3, 'Compra', 60.00, TO_DATE('2024-08-22', 'YYYY-MM-DD'), 'Compra de almuerzo.');
INSERT INTO usuarioDondePapa.transacciones (id_usuario, tipo, monto, fecha, descripcion)
    VALUES (1, 'Transferencia', 150.00, TO_DATE('2024-08-24', 'YYYY-MM-DD'), 'Transferencia a cuenta externa.');
INSERT INTO usuarioDondePapa.transacciones (id_usuario, tipo, monto, fecha, descripcion)
    VALUES (2, 'Transferencia', 200.00, TO_DATE('2024-08-19', 'YYYY-MM-DD'), 'Transferencia de saldo.');
INSERT INTO usuarioDondePapa.transacciones (id_usuario, tipo, monto, fecha, descripcion)
    VALUES (3, 'Pago de factura', 95.00, TO_DATE('2024-08-21', 'YYYY-MM-DD'), 'Pago de factura 456.');
INSERT INTO usuarioDondePapa.transacciones (id_usuario, tipo, monto, fecha, descripcion)
    VALUES (2, 'Reembolso', 40.00, TO_DATE('2024-08-23', 'YYYY-MM-DD'), 'Reembolso de cancelacion.');

CREATE OR REPLACE FUNCTION OBTENER_TRANSACCIONES_X_USUARIO (
    p_id_usuario IN NUMBER
)
RETURN SYS_REFCURSOR
AS
    transacciones_cursor SYS_REFCURSOR;
BEGIN
    OPEN transacciones_cursor FOR
        SELECT id_transaccion, tipo, monto, fecha, descripcion
        FROM TRANSACCIONES
        WHERE id_usuario = p_id_usuario;
    RETURN transacciones_cursor;
END;

DECLARE
    v_cursor SYS_REFCURSOR;
    v_id_transaccion usuarioDondePapa.TRANSACCIONES.id_transaccion%TYPE;
    v_tipo usuarioDondePapa.TRANSACCIONES.tipo%TYPE;
    v_monto usuarioDondePapa.TRANSACCIONES.monto%TYPE;
    v_fecha usuarioDondePapa.TRANSACCIONES.fecha%TYPE;
    v_descripcion usuarioDondePapa.TRANSACCIONES.descripcion%TYPE;
BEGIN
    v_cursor := OBTENER_TRANSACCIONES_X_USUARIO(2);
    
    LOOP
        FETCH v_cursor INTO v_id_transaccion, v_tipo, v_monto, v_fecha, v_descripcion;
        EXIT WHEN v_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Transaccion: ' || v_id_transaccion || CHR(10) ||
    'Tipo: ' || v_tipo || CHR(10) || 
    'Monto: ' || v_monto || CHR(10) ||
    'Fecha: ' || v_fecha || CHR(10) ||
    'Descripcion: ' || v_descripcion || CHR(10));
    END LOOP;
    CLOSE v_cursor;
END;

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

-- 8. Funcion que calcula el total de ingresos generados por un producto almacenado en VENTAs
CREATE OR REPLACE FUNCTION CALCULAR_VENTAS_X_PLATO (
    p_id_plato NUMBER
)
RETURN NUMBER
IS
    v_total_ventas NUMBER := 0;
BEGIN
    SELECT SUM(CANTIDAD * PRECIO)
    INTO v_total_ventas
    FROM VENTA
    WHERE ID_PLATO = p_id_plato;
    
    RETURN NVL(v_total_ventas, 0);
END;

SELECT CALCULAR_VENTAS_X_PLATO(10) "TOTAL VENTAS" FROM DUAL;

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

-- 9. Funcionar para calcular el preico promedio de los platos, aunque aparente
-- innecesario, esto puede ser de ayuda cuando se requiera hacer un análisis 
-- después de la modificación de precios en productos, ingreso/departura de otros, etc.
CREATE OR REPLACE FUNCTION CALCULAR_AVG_PRECIO_PLATOS
RETURN NUMBER
IS
    v_avg_precio NUMBER := 0;
BEGIN
    SELECT ROUND(AVG(PRECIO), 2) -- Esto para mostrar maximo 2 decimales
    INTO v_avg_precio
    FROM PLATO
    WHERE DISPONIBLE = 1;
    
    RETURN NVL(v_avg_precio, 0);
END;

SELECT CALCULAR_AVG_PRECIO_PLATOS PROMEDIO FROM DUAL;

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

-- 10. Funcion que imprime por medio de un DMBS.OUTPUT, los platos agotados.
CREATE OR REPLACE FUNCTION OBTENER_PLATOS_AGOTADO
RETURN SYS_REFCURSOR
IS
    v_cursor SYS_REFCURSOR;
BEGIN
    OPEN v_cursor FOR
    SELECT 
        ID_PLATO, DESCRIPCION, DETALLE, PRECIO, EXISTENCIAS
    FROM PLATO
    WHERE
        EXISTENCIAS = 0;
        
    RETURN v_cursor;
END;

INSERT INTO PLATO (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Elote con Mantequilla', 'Rico elote en pincho cubierto en mantequilla derretida.', 2500, 0, 13, 0, 'https://editorialtelevisa.brightspotcdn.com/dims4/default/fe4c40d/2147483647/strip/true/crop/560x560+220+0/resize/1000x1000!/quality/90/?url=https%3A%2F%2Fk2-prod-editorial-televisa.s3.us-east-1.amazonaws.com%2Fbrightspot%2Fwp-content%2Fuploads%2F2018%2F12%2Felotes-mantequilla-maple-romero.jpg'); 

INSERT INTO PLATO (descripcion, detalle, precio, existencias, id_categoria, disponible, ruta_imagen) VALUES 
    ('Pasta Carbonara', 'Clasica pasta italiana con cachete de cerdo y queso pecorino', 4000, 0, 8, 0, 'https://i.blogs.es/8819e1/carbonara-rec/650_1200.jpg'); 

DECLARE
    v_cursor SYS_REFCURSOR;
    v_id_plato PLATO.id_plato%TYPE;
    v_descripcion PLATO.descripcion%TYPE;
    v_detalle PLATO.detalle%TYPE;
    v_precio PLATO.precio%TYPE;
    v_existencias PLATO.existencias%TYPE;
BEGIN
    v_cursor := OBTENER_PLATOS_AGOTADO;
    
    LOOP
        FETCH v_cursor INTO v_id_plato, v_descripcion, v_detalle, v_precio, v_existencias;
        EXIT WHEN v_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Plato: ' || v_id_plato || CHR(10) ||
    'Descripcion: ' || v_descripcion || CHR(10) || 
    'Detalle: ' || v_detalle || CHR(10) ||
    'Precio: ' || v_precio || CHR(10) ||
    'Existencias: ' || v_existencias || CHR(10));
    END LOOP;
    CLOSE v_cursor;
END;

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

-- 11. Funcion para mostrar los primeros x (maximo) platos en ser los más popualres
CREATE OR REPLACE FUNCTION OBTENER_PLATOS_POPULARES (
    maximo NUMBER
)
RETURN SYS_REFCURSOR
IS
    platos_pop SYS_REFCURSOR;
BEGIN
    OPEN platos_pop FOR
    SELECT 
        p.ID_PLATO , p.DESCRIPCION, SUM(v.CANTIDAD) AS total
    FROM
        PLATO p
    JOIN
        VENTA v ON p.ID_PLATO = v.ID_PLATO
    GROUP BY 
        p.ID_PLATO, p.DESCRIPCION
    ORDER BY
        total DESC
    FETCH FIRST maximo ROWS ONLY;
    
    RETURN platos_pop;
END;
   
DECLARE
    v_cursor SYS_REFCURSOR;
    v_id_plato PLATO.id_plato%TYPE;
    v_descripcion PLATO.descripcion%TYPE;
    v_total NUMBER;
BEGIN
    v_cursor := OBTENER_PLATOS_POPULARES(5);
    
    LOOP
        FETCH v_cursor INTO v_id_plato, v_descripcion, v_total;
        EXIT WHEN v_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ID Plato: ' || v_id_plato || CHR(10) ||
    'Descripcion: ' || v_descripcion || CHR(10) || 
    'Total Vendidos: ' || v_total || CHR(10));
    END LOOP;
    CLOSE v_cursor;
END; 
    
SELECT OBTENER_PLATOS_POPULARES(5) FROM DUAL;

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
    
-- 12. Funcion para obtener la ultima factura registrada por x usuario
CREATE OR REPLACE FUNCTION OBTENER_ULTIMA_FACTURA_USUARIO (
    p_id_usuario IN NUMBER
)
RETURN usuarioDondePapa.FACTURA%ROWTYPE
IS
    v_ultima_factura usuarioDondePapa.factura%ROWTYPE;
BEGIN
    
    BEGIN
        SELECT *
        INTO 
            v_ultima_factura
        FROM (
            SELECT *
            FROM FACTURA
            WHERE ID_USUARIO = p_id_usuario
            ORDER BY FECHA DESC
        )
        WHERE ROWNUM = 1;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN NULL;
    END;
    
    RETURN v_ultima_factura;
END;
    
SELECT * FROM FACTURA;
    
DECLARE
    v_factura usuarioDondePapa.FACTURA%ROWTYPE;
    v_id_usuario NUMBER;
BEGIN
    v_factura := OBTENER_ULTIMA_FACTURA_USUARIO(3);
    
    IF v_factura.ID_FACTURA IS NOT NULL THEN
        DBMS_OUTPUT.PUT_LINE('ID Factura: ' || v_factura.id_factura);
        DBMS_OUTPUT.PUT_LINE('Fecha: ' || v_factura.fecha);
        DBMS_OUTPUT.PUT_LINE('Total: ' || v_factura.total);
        DBMS_OUTPUT.PUT_LINE('Estado: ' || v_factura.estado);
    ELSE
        DBMS_OUTPUT.PUT_LINE('No se encontraron facturas para el usuario.');
    END IF;
END;

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
    
-- 13. Funcion para obtener el rol de un usuario
CREATE OR REPLACE FUNCTION OBTENER_ROLES_POR_USUARIO (
    p_id_usuario IN NUMBER
) 
RETURN SYS_REFCURSOR
AS
    v_cursor SYS_REFCURSOR;
BEGIN
    OPEN v_cursor FOR
        SELECT 
            NOMBRE AS Rol
        FROM 
           ROL
        WHERE 
            ID_USUARIO = p_id_usuario;
            
    RETURN v_cursor;
END;
    
DECLARE
    v_cursor SYS_REFCURSOR;
    v_rol usuarioDondePapa.ROL.nombre%TYPE;
BEGIN
    v_cursor := OBTENER_ROLES_POR_USUARIO(1);
    
    LOOP
        FETCH v_cursor INTO v_rol;
        EXIT WHEN v_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ROL: ' || v_rol || CHR(10));
    END LOOP;
    
    CLOSE v_cursor;
END; 

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

-- 14. Funcion para rapidamente buscar el contacto de una reserva en caso de una emergencia.
CREATE OR REPLACE FUNCTION OBTENER_CONTACTO_RESERVACION(
    p_id_reservacion IN NUMBER
) 
RETURN VARCHAR2
IS
    v_contacto VARCHAR2(255);
BEGIN
    SELECT CONTACTO
    INTO v_contacto
    FROM RESERVACION
    WHERE ID_RESERVACION = p_id_reservacion;

    RETURN v_contacto;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'No tenemos esa reservación registrada';
END;

SELECT OBTENER_CONTACTO_RESERVACION(41) CONTACTO FROM DUAL;


SELECT * FROM RESERVACION;

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

-- 15. Esta función va de la mano con la anterior, ya que una vez obtenido el
-- numero de telefono, se puede buscar el nombre y numero de mesa del usuario
-- que reservó en caso de emergencia.
CREATE OR REPLACE FUNCTION OBTENER_INFO_POR_CONTACTO (
    p_contacto IN VARCHAR2
)
RETURN SYS_REFCURSOR
AS
    v_cursor SYS_REFCURSOR;
BEGIN
    OPEN v_cursor FOR
    SELECT 
        NOMBRE,
        NUMERO_DE_MESA
    FROM 
        RESERVACION
    WHERE 
        CONTACTO = p_contacto;
    
    RETURN v_cursor;
END;

DECLARE
    v_cursor SYS_REFCURSOR;
    v_nombre RESERVACION.nombre%TYPE;
    v_numero_mesa RESERVACION.numero_de_mesa%TYPE;
BEGIN
    v_cursor := OBTENER_INFO_POR_CONTACTO('555-1234');
    
    LOOP
        FETCH v_cursor INTO v_nombre, v_numero_mesa;
        EXIT WHEN v_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('A nombre de: ' || v_nombre || CHR(10) ||
    'Numero de Mesa: ' || v_numero_mesa || CHR(10));
    END LOOP;
    CLOSE v_cursor;
END; 

--------------------------------------------------------
-- PAQUETES
--------------------------------------------------------
SELECT * FROM CATEGORIA;
-- 1. 
CREATE OR REPLACE PACKAGE pckg_GESTION_CATEGORIAS AS

    PROCEDURE INSERT_CATEGORIA (
        p_descripcion IN VARCHAR2,
        p_disponible IN NUMBER,
        p_ruta_imagen IN VARCHAR2
    );
    
    PROCEDURE UPDATE_CATEGORIA (
        p_id_categoria IN NUMBER,
        p_descripcion IN VARCHAR2,
        p_disponible IN NUMBER,
        p_ruta_imagen IN VARCHAR2
    );
    
    PROCEDURE DELETE_CATEGORIA (
        p_id_categoria IN NUMBER
    );

END pckg_GESTION_CATEGORIAS;

CREATE















